### ISSUE TITLE
Quarkus 1.5.1 : NoSuchMethodError: QuarkusBootstrap.getApplicationRoot()Ljava/nio/file/Path

### ISSUE THREAD

**Issue by agoncal** [quarkusio/quarkus#9966]
**Describe the bug**
Since upgrading Quarkus from 1.5.0.Final to 1.5.1.Final I have a strange bug. If you run a test on its own, or from the root directory (root `pom.xml`) with Maven (`mvn clean test`), it works. But if you `cd` a sub-directory and run `mvn clean test` from a sub-module, it breaks at the first test (no matter which one) with the following exception:

```
[INFO] Running org.agoncal.fascicle.quarkus.core.cdi.events.BookServiceTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.711 s <<< FAILURE! - in org.agoncal.fascicle.quarkus.core.cdi.events.BookServiceTest
[ERROR] shouldCheckEvents  Time elapsed: 0.008 s  <<< ERROR!
java.lang.RuntimeException: java.lang.NoSuchMethodError: io.quarkus.bootstrap.app.QuarkusBootstrap.getApplicationRoot()Ljava/nio/file/Path;
Caused by: java.lang.NoSuchMethodError: io.quarkus.bootstrap.app.QuarkusBootstrap.getApplicationRoot()Ljava/nio/file/Path;
```

I don't use the Maven wrapper generated by Quarkus but Maven 3.6.3.

See #5680

**To Reproduce**
1. Checkout the code in https://github.com/agoncal/agoncal-fascicle-quarkus.git
2. Go to `core` directory
3. `mvn clean test` -> SUCCESS
4. Update Quarkus version 1.5.0 to 1.5.1 (`<quarkus-plugin.version>` and `<quarkus.platform.version>`)
5. From the root directory `$ mvn clean test` -> SUCCESS
6. From a subdirectory `core$ mvn clean test` -> FAIL

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Darwin iMac-Pro-de-Antonio.local 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64
 - Output of `java -version`: java version "11.0.6" 2020-01-14 LTS
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.5.1.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.3

**Additional context**
I have also reproduced this bug on a second Mac (different OSX version and Java 11.0.5)

**Comment by jaikiran** [comment]
>> If you run a test on its own, or from the root directory (root pom.xml) with Maven (mvn clean test), it works. But if you cd a sub-directory and run mvn clean test from a sub-module, it breaks at the first test (no matter which one) with the following exception:

I see that your `pom.xml`[1] of these child modules and even the parent module is `1.0` and `1.0-SNAPSHOT`. So it's likely that Maven is picking up a previously published artifact/dependency of your project from your local Maven repository and that project of yours perhaps is using an old dependency of Quarkus? Maven considers "released" versions (like 1.0) as immutable so I guess that's playing some kind of role here.

[1] https://github.com/agoncal/agoncal-fascicle-quarkus/blob/master/pom.xml#L8

**Comment by agoncal** [comment]
Thanks @jaikiran I was looking everywhere except my own pom versions. Changed all my versionning to 1.0-SNAPSHOT and it's now working. #Thanks
