### ISSUE TITLE
After upgrade to 2.0.1 Gradle is no longer finding generated sources

### ISSUE THREAD

**Issue by tanadeau** [quarkusio/quarkus#18541]
## Describe the bug
Exact same annotation processors, Gradle version, etc. works with 1.13.7.Final; however, on upgrade to 2.0.0.Final or 2.0.1.Final, I get hundreds of errors caused by not finding generated classes.

### Expected behavior
All sources in `build/generated/sources/annotationProcessor/java/main` are seen during compilation.

### Actual behavior
Sources in directory above are not found creating many `cannot find symbol` errors.

## To Reproduce
I need to create a reproducer with a much smaller annotation processor library.

1. 
2. 
3. 

### Configuration
```properties
# Add your application.properties here, if applicable.

```

### Screenshots
(If applicable, add screenshots to help explain your problem.)

### Output of `uname -a` or `ver`
```
Darwin C02YK01PLVCG-ML 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64
```

### Output of `java -version`
```
openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)
```

### Quarkus version or git rev
2.0.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
```
------------------------------------------------------------
Gradle 7.1.1
------------------------------------------------------------

Build time:   2021-07-02 12:16:43 UTC
Revision:     774525a055494e0ece39f522ac7ad17498ce032c

Kotlin:       1.4.31
Groovy:       3.0.7
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.11 (AdoptOpenJDK 11.0.11+9)
OS:           Mac OS X 11.4 x86_64
```

## Additional context
(Add any other context about the problem here.)

**Comment by tanadeau** [comment]
I have a feeling it's due to https://github.com/quarkusio/quarkus/commit/d8fd0b974b89a36018995475a44f40fa04dcdd55

**Comment by glefloch** [comment]
Thanks for reporting this @tanadeau. 

I generated a sample project from `code.quarkus.io` with `kotlin` and `grpc` extension. 
I'm not able to reproduce this error. I tried with both gradle 6.9 and 7.1.1. Could you share a reproducer?

**Comment by tanadeau** [comment]
Thanks for taking a look. We're using our own annotation processors so I think it may be the fact that they are not in an extension. I'll see if I can make a small reproducer.

**Comment by tanadeau** [comment]
I found the issue. This is related to #17618. We have a "-Werror" passed to javac, and the warnings coming from microprofile-config-api were causing the compilation round to fail before the generated sources were processed.
