### ISSUE TITLE
Agroal has a reference to a Netty class while not depending on it

### ISSUE THREAD

**Issue by wjglerum** [quarkusio/quarkus#19247]
### Describe the bug

After upgrading our project to Quarkus 2.1.1 from 2.1.0 we noticed that our database integration tests started to fail.

Quarkus tries to start, but crashes directly with:
```
java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus
Caused by: java.lang.RuntimeException: Failed to start quarkus
Caused by: java.lang.NoClassDefFoundError: io/netty/util/concurrent/FastThreadLocal
Caused by: java.lang.ClassNotFoundException: io.netty.util.concurrent.FastThreadLocal
```

Could this be related to the work done here https://github.com/quarkusio/quarkus/pull/18925? 

### How to Reproduce?

Couldn't get a simple reproducer right now.

### Output of `uname -a` or `ver`

```
Darwin Willems-MBP.i.btp34.nl 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64
```

### Output of `java -version`

```
openjdk 11.0.11 2021-04-20 OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9) OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)
```

### Quarkus version or git rev

`2.1.1.Final`

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

```
Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d) Maven home: /Users/wjglerum/.m2/wrapper/dists/apache-maven-3.8.1-bin/2l5mhf2pq2clrde7f7qp1rdt5m/apache-maven-3.8.1 Java version: 11.0.11, vendor: AdoptOpenJDK, runtime: /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home Default locale: en_NL, platform encoding: UTF-8 OS name: "mac os x", version: "11.4", arch: "x86_64", family: "mac"
```

**Comment by wjglerum** [comment]
Alright, I think I found something. We are using a multi-module maven project, where we have a dedicated database module with Quarkus dependencies, but it doesn't include any RESTeasy dependencies. Once I add `quarkus-resteasy` to that module the integration tests pass again.

Provided a minimal reproducer here https://github.com/wjglerum/quarkus-panache

**Comment by gsmet** [comment]
Good catch. The issue is that the new `QuarkusConnectionCache` in Agroal has a hard dependency to Netty... and it compiles because the optional `quarkus-smallrye-health` bring Netty into the compile classpath of the extension.

We have two options here:
- either have Agroal dependent on Netty - not sure it's a good idea,
- or only use this cache if Netty is around.

@stuartwdouglas I can do the ground work but I would appreciate your opinion on what is best.

**Comment by Sanne** [comment]
Optional dependencies strike again.

Is it even possible to run a Quarkus app w/o Netty nowadays?  If it's not possible we should just add the hard dependency.

**Comment by xstefank** [comment]
looking into `quarkus-smallrye-health` dependency tree we pull netty through `io.quarkus:quarkus-vertx-http`,`io.quarkus:quarkus-arc-deployment`, and `io.quarkus:quarkus-vertx-http-deployment:`. Should I try to investigate if we can exclude netty? Do other extensions exclude it from these dependencies?

**Comment by Sanne** [comment]
hi @xstefank ! AFAIK (but would like to hear confirmations from others) we almost always require Netty - perhaps only with CLI apps is it not required but I'm not sure. I'd suggest to get an authoritative answer about that first (Stuart will likely comment when he's back), so to not do such work without need.

**Comment by stuartwdouglas** [comment]
It is definitely possible to run without Netty, e.g. a CLI hibernate app. That said most extensions that do anything with the network rely on it.
