### ISSUE TITLE
Quarksu command mode application issue when upgrading to 2.13.0 from 2.12.3

### ISSUE THREAD

**Issue by argenstijn** [quarkusio/quarkus#28317]
Hi,

When u upgrade from 2.12.3 to 2.13.0 i see the following exception

_**Picked up JAVA_TOOL_OPTIONS: -Djava.util.logging.manager=org.jboss.logmanager.LogManager
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at io.quarkus.launcher.QuarkusLauncher.launch(QuarkusLauncher.java:58)
	at io.quarkus.runtime.Quarkus.launchFromIDE(Quarkus.java:97)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:84)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
	at com.nn.aav.insurance.business.boot.boundary.QuarkusBoot.main(QuarkusBoot.java:14)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.launcher.QuarkusLauncher.launch(QuarkusLauncher.java:56)
	... 4 more
Caused by: java.lang.NoSuchMethodError: 'boolean io.quarkus.bootstrap.app.CuratedApplication.hasReloadableArtifacts()'
	at io.quarkus.deployment.dev.QuarkusCompiler.<init>(QuarkusCompiler.java:68)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.setupRuntimeCompilation(IsolatedDevModeMain.java:252)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:441)
	at io.quarkus.deployment.dev.IDEDevModeMain.accept(IDEDevModeMain.java:71)
	at io.quarkus.deployment.dev.IDEDevModeMain.accept(IDEDevModeMain.java:28)
	at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:147)
	at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:102)
	at io.quarkus.bootstrap.IDELauncherImpl.launch(IDELauncherImpl.java:92)
	... 9 more**_

**How to reproduce**

yet **no** a reproduceble artifact!.

But using the following dependencies

<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi-ooxml</artifactId>
			<version>5.2.3</version>
			<exclusions>
				<exclusion>
					<groupId>xml-apis</groupId>
					<artifactId>xml-apis</artifactId>

				</exclusion>
				<exclusion>
					<groupId>xalan</groupId>
					<artifactId>xalan</artifactId>
				</exclusion>

				<exclusion>
					<groupId>org.apache.logging.log4j</groupId>
					<artifactId>log4j-api</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		
		<dependency>
			<groupId>org.jboss.logmanager</groupId>
			<artifactId>log4j2-jboss-logmanager</artifactId>
		</dependency>

		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-vertx</artifactId>
		</dependency>

		<dependency>
			<groupId>io.smallrye.reactive</groupId>
			<artifactId>smallrye-mutiny-vertx-web-client</artifactId>
		</dependency>

		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-qute</artifactId>
		</dependency>

		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-jaxb</artifactId>
		</dependency>

		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-arc</artifactId>
		</dependency>

		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-resteasy</artifactId>
		</dependency>

And calling this method through a Intellij runscript.

@QuarkusMain
public class QuarkusBoot {

    public static void main(String[] args) {      
       Quarkus.run(........., args);  
      
    }

}

**Output of uname -a or ver**

Microsoft Windows [Version 10.0.19044.2006]

**Output of java -version**

openjdk version "11.0.16" 2022-07-19 LTS
OpenJDK Runtime Environment Corretto-11.0.16.8.1 (build 11.0.16+8-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.16.8.1 (build 11.0.16+8-LTS, mixed mode)

**Quarkus version or git rev**

2.12.3.Final

**Build tool (ie. output of mvnw --version or gradlew --version)**

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)

**Comment by gsmet** [comment]
Are you sure you don't have different versions of Quarkus mixed up? Especially that the Quarkus Maven plugin and Quarkus dependencies version are the same?

If it is, we will need a small reproducer (i.e. a small Maven project reproducing the issue).

**Comment by argenstijn** [comment]
Can be closed. 

I update the pom but the maven intelij plugin did not update the dependency. So that was the issue.
