### ISSUE TITLE
kogito-quickstart does not work with quarkus-universe-bom on 1.12.2.Final

### ISSUE THREAD

**Issue by jsmrcka** [quarkusio/quarkus#15684]
**Describe the bug**
When using `quarkus-universe-bom`, the module throws an exception.
Possibly some issue with Kogito versions in the quickstart vs. universe-bom?

**Expected behavior**
Module runs without errors.

**Actual behavior**
Fails with exception:
```
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step org.kie.kogito.quarkus.deployment.KogitoAssetsProcessor#generateModel threw an exception: java.lang.NoSuchMethodError: 'void org.drools.compiler.kie.builder.impl.KieBuilderImpl.setDefaultsforEmptyKieModule(org.kie.api.builder.model.KieModuleModel)'
	at org.kie.kogito.codegen.rules.IncrementalRuleCodegen.<init>(IncrementalRuleCodegen.java:130)
	at org.kie.kogito.codegen.rules.IncrementalRuleCodegen.ofResources(IncrementalRuleCodegen.java:113)
	at org.kie.kogito.codegen.rules.IncrementalRuleCodegen.ofCollectedResources(IncrementalRuleCodegen.java:99)
	at org.kie.kogito.codegen.utils.ApplicationGeneratorDiscovery.loadGenerators(ApplicationGeneratorDiscovery.java:54)
	at org.kie.kogito.codegen.utils.ApplicationGeneratorDiscovery.discover(ApplicationGeneratorDiscovery.java:42)
	at org.kie.kogito.quarkus.deployment.KogitoAssetsProcessor.generateModel(KogitoAssetsProcessor.java:146)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:920)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

**To Reproduce**

```
git clone git@github.com:quarkusio/quarkus-quickstarts.git
git checkout 1.12.2.Final
cd quarkus-quickstarts/kogito-quickstart
```
```
mvn clean verify -Dquarkus.platform.group-id=io.quarkus -Dquarkus.platform.artifact-id=quarkus-universe-bom
```

**Environment:**
 - Output of `java -version`:
 ```
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)
```
 - Quarkus version: 1.12.2.Final
 - Build tool: Apache Maven 3.6.3

**Comment by jsmrcka** [comment]
Fixed by https://github.com/quarkusio/quarkus-quickstarts/pull/853.
