### PR TITLE
Bump Gradle version to 9.0.0

### PR DESCRIPTION
**Pull request by Eng-Fouad**
- Release notes: https://docs.gradle.org/9.0.0/release-notes.html

### CODE REVIEW

**Comment by Eng-Fouad** [comment]
@aloubyansky CI fails now with Gradle 9.0 after merging https://github.com/quarkusio/quarkus/pull/49224 (I think)

> 2025-08-01T13:52:43.9638815Z [INFO] Quarkus - Gradle Model ............................. FAILURE [01:42 min]

```
2025-08-01T13:52:44.3521633Z [ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.5.1:exec (gradle) on project quarkus-gradle-model: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]
2025-08-01T13:52:44.3523399Z org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.5.1:exec (gradle) on project quarkus-gradle-model: Command execution failed.
2025-08-01T13:52:44.3524685Z     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:333)
2025-08-01T13:52:44.3525526Z     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:316)
2025-08-01T13:52:44.3526330Z     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:212)
2025-08-01T13:52:44.3527801Z     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:174)
2025-08-01T13:52:44.3529867Z     at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:75)
2025-08-01T13:52:44.3530666Z     at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:162)
2025-08-01T13:52:44.3531537Z     at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
2025-08-01T13:52:44.3532663Z     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:159)
2025-08-01T13:52:44.3533580Z     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
2025-08-01T13:52:44.3534796Z     at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:193)
2025-08-01T13:52:44.3535965Z     at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:180)
2025-08-01T13:52:44.3536813Z     at java.util.concurrent.FutureTask.run (FutureTask.java:264)
2025-08-01T13:52:44.3537389Z     at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:539)
2025-08-01T13:52:44.3537909Z     at java.util.concurrent.FutureTask.run (FutureTask.java:264)
2025-08-01T13:52:44.3538547Z     at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1136)
2025-08-01T13:52:44.3539296Z     at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:635)
2025-08-01T13:52:44.3540032Z     at java.lang.Thread.run (Thread.java:840)
2025-08-01T13:52:44.3540558Z Caused by: org.apache.maven.plugin.MojoExecutionException: Command execution failed.
2025-08-01T13:52:44.3541141Z     at org.codehaus.mojo.exec.ExecMojo.execute (ExecMojo.java:469)
2025-08-01T13:52:44.3541722Z     at jdk.internal.reflect.GeneratedMethodAccessor24.invoke (Unknown Source)
2025-08-01T13:52:44.3542507Z     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
2025-08-01T13:52:44.3543220Z     at java.lang.reflect.Method.invoke (Method.java:569)
2025-08-01T13:52:44.3543679Z     at com.gradle.maven.cache.extension.c.n.a (SourceFile:53)
2025-08-01T13:52:44.3544148Z     at com.gradle.maven.cache.extension.c.d.a (SourceFile:27)
2025-08-01T13:52:44.3544617Z     at com.gradle.maven.cache.extension.c.q.a (SourceFile:23)
2025-08-01T13:52:44.3545052Z     at com.gradle.maven.cache.extension.c.j.a (SourceFile:28)
2025-08-01T13:52:44.3545450Z     at com.gradle.maven.cache.extension.c.p.a (SourceFile:27)
2025-08-01T13:52:44.3545918Z     at com.gradle.maven.cache.extension.c.b.c (SourceFile:118)
2025-08-01T13:52:44.3546379Z     at com.gradle.maven.cache.extension.c.b.a (SourceFile:62)
2025-08-01T13:52:44.3546830Z     at com.gradle.maven.cache.extension.c.g.a (SourceFile:27)
2025-08-01T13:52:44.3547285Z     at com.gradle.maven.cache.extension.c.a.a (SourceFile:46)
2025-08-01T13:52:44.3547871Z     at com.gradle.maven.cache.extension.c.o.a (SourceFile:18)
2025-08-01T13:52:44.3548377Z     at com.gradle.maven.cache.extension.c.a.a (SourceFile:46)
2025-08-01T13:52:44.3548824Z     at com.gradle.maven.cache.extension.c.c.a (SourceFile:26)
2025-08-01T13:52:44.3549295Z     at com.gradle.maven.cache.extension.c.h$1.run (SourceFile:35)
2025-08-01T13:52:44.3550078Z     at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute (SourceFile:29)
2025-08-01T13:52:44.3550814Z     at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute (SourceFile:26)
2025-08-01T13:52:44.3551529Z     at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute (SourceFile:66)
2025-08-01T13:52:44.3552077Z     at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute (SourceFile:59)
2025-08-01T13:52:44.3552544Z     at org.gradle.internal.operations.DefaultBuildOperationRunner.execute (SourceFile:166)
2025-08-01T13:52:44.3553019Z     at org.gradle.internal.operations.DefaultBuildOperationRunner.execute (SourceFile:59)
2025-08-01T13:52:44.3553466Z     at org.gradle.internal.operations.DefaultBuildOperationRunner.run (SourceFile:47)
2025-08-01T13:52:44.3553833Z     at com.gradle.maven.cache.extension.c.h.a (SourceFile:31)
2025-08-01T13:52:44.3554116Z     at com.gradle.maven.cache.extension.c.m.a (SourceFile:80)
2025-08-01T13:52:44.3554443Z     at com.gradle.maven.cache.extension.g.b.lambda$createProxy$0 (SourceFile:76)
2025-08-01T13:52:44.3554766Z     at jdk.proxy48.$Proxy155.execute (Unknown Source)
2025-08-01T13:52:44.3555139Z     at com.gradle.maven.scan.extension.internal.d.b.executeMojo (SourceFile:116)
2025-08-01T13:52:44.3555565Z     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:328)
2025-08-01T13:52:44.3556039Z     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:316)
2025-08-01T13:52:44.3556471Z     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:212)
2025-08-01T13:52:44.3556911Z     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:174)
2025-08-01T13:52:44.3557348Z     at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:75)
2025-08-01T13:52:44.3557782Z     at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:162)
2025-08-01T13:52:44.3558267Z     at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
2025-08-01T13:52:44.3558759Z     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:159)
2025-08-01T13:52:44.3559272Z     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
2025-08-01T13:52:44.3560762Z     at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:193)
2025-08-01T13:52:44.3562005Z     at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:180)
2025-08-01T13:52:44.3562873Z     at java.util.concurrent.FutureTask.run (FutureTask.java:264)
2025-08-01T13:52:44.3563523Z     at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:539)
2025-08-01T13:52:44.3564153Z     at java.util.concurrent.FutureTask.run (FutureTask.java:264)
2025-08-01T13:52:44.3564800Z     at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1136)
2025-08-01T13:52:44.3565618Z     at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:635)
2025-08-01T13:52:44.3566232Z     at java.lang.Thread.run (Thread.java:840)
2025-08-01T13:52:44.3566906Z Caused by: org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
2025-08-01T13:52:44.3567798Z     at org.apache.commons.exec.DefaultExecutor.executeInternal (DefaultExecutor.java:394)
2025-08-01T13:52:44.3568478Z     at org.apache.commons.exec.DefaultExecutor.execute (DefaultExecutor.java:292)
2025-08-01T13:52:44.3569213Z     at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:903)
2025-08-01T13:52:44.3570066Z     at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:863)
2025-08-01T13:52:44.3570624Z     at org.codehaus.mojo.exec.ExecMojo.execute (ExecMojo.java:454)
2025-08-01T13:52:44.3571183Z     at jdk.internal.reflect.GeneratedMethodAccessor24.invoke (Unknown Source)
2025-08-01T13:52:44.3571947Z     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
2025-08-01T13:52:44.3572627Z     at java.lang.reflect.Method.invoke (Method.java:569)
2025-08-01T13:52:44.3573087Z     at com.gradle.maven.cache.extension.c.n.a (SourceFile:53)
2025-08-01T13:52:44.3573551Z     at com.gradle.maven.cache.extension.c.d.a (SourceFile:27)
2025-08-01T13:52:44.3573959Z     at com.gradle.maven.cache.extension.c.q.a (SourceFile:23)
2025-08-01T13:52:44.3574405Z     at com.gradle.maven.cache.extension.c.j.a (SourceFile:28)
2025-08-01T13:52:44.3574832Z     at com.gradle.maven.cache.extension.c.p.a (SourceFile:27)
2025-08-01T13:52:44.3575255Z     at com.gradle.maven.cache.extension.c.b.c (SourceFile:118)
2025-08-01T13:52:44.3575712Z     at com.gradle.maven.cache.extension.c.b.a (SourceFile:62)
2025-08-01T13:52:44.3576186Z     at com.gradle.maven.cache.extension.c.g.a (SourceFile:27)
2025-08-01T13:52:44.3576693Z     at com.gradle.maven.cache.extension.c.a.a (SourceFile:46)
2025-08-01T13:52:44.3577168Z     at com.gradle.maven.cache.extension.c.o.a (SourceFile:18)
2025-08-01T13:52:44.3577611Z     at com.gradle.maven.cache.extension.c.a.a (SourceFile:46)
2025-08-01T13:52:44.3578184Z     at com.gradle.maven.cache.extension.c.c.a (SourceFile:26)
2025-08-01T13:52:44.3578685Z     at com.gradle.maven.cache.extension.c.h$1.run (SourceFile:35)
2025-08-01T13:52:44.3579570Z     at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute (SourceFile:29)
2025-08-01T13:52:44.3580328Z     at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute (SourceFile:26)
2025-08-01T13:52:44.3580990Z     at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute (SourceFile:66)
2025-08-01T13:52:44.3581762Z     at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute (SourceFile:59)
2025-08-01T13:52:44.3582554Z     at org.gradle.internal.operations.DefaultBuildOperationRunner.execute (SourceFile:166)
2025-08-01T13:52:44.3583356Z     at org.gradle.internal.operations.DefaultBuildOperationRunner.execute (SourceFile:59)
2025-08-01T13:52:44.3584104Z     at org.gradle.internal.operations.DefaultBuildOperationRunner.run (SourceFile:47)
2025-08-01T13:52:44.3584658Z     at com.gradle.maven.cache.extension.c.h.a (SourceFile:31)
2025-08-01T13:52:44.3585053Z     at com.gradle.maven.cache.extension.c.m.a (SourceFile:80)
2025-08-01T13:52:44.3585600Z     at com.gradle.maven.cache.extension.g.b.lambda$createProxy$0 (SourceFile:76)
2025-08-01T13:52:44.3586121Z     at jdk.proxy48.$Proxy155.execute (Unknown Source)
2025-08-01T13:52:44.3586642Z     at com.gradle.maven.scan.extension.internal.d.b.executeMojo (SourceFile:116)
2025-08-01T13:52:44.3587343Z     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:328)
2025-08-01T13:52:44.3588076Z     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:316)
2025-08-01T13:52:44.3588817Z     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:212)
2025-08-01T13:52:44.3589704Z     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:174)
2025-08-01T13:52:44.3590452Z     at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:75)
2025-08-01T13:52:44.3591144Z     at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:162)
2025-08-01T13:52:44.3591953Z     at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
2025-08-01T13:52:44.3592738Z     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:159)
2025-08-01T13:52:44.3593714Z     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
2025-08-01T13:52:44.3594820Z     at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:193)
2025-08-01T13:52:44.3595901Z     at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:180)
2025-08-01T13:52:44.3596729Z     at java.util.concurrent.FutureTask.run (FutureTask.java:264)
2025-08-01T13:52:44.3597311Z     at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:539)
2025-08-01T13:52:44.3597854Z     at java.util.concurrent.FutureTask.run (FutureTask.java:264)
2025-08-01T13:52:44.3598470Z     at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1136)
2025-08-01T13:52:44.3599168Z     at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:635)
2025-08-01T13:52:44.3599875Z     at java.lang.Thread.run (Thread.java:840)
2025-08-01T13:52:44.3600216Z [ERROR] 
2025-08-01T13:52:44.3600692Z [ERROR] Re-run Maven using the -X switch to enable full debug logging.
2025-08-01T13:52:44.3601139Z [ERROR] 
2025-08-01T13:52:44.3601661Z [ERROR] For more information about the errors and possible solutions, please read the following articles:
2025-08-01T13:52:44.3602423Z [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
2025-08-01T13:52:44.3602902Z [ERROR] 
2025-08-01T13:52:44.3603272Z [ERROR] After correcting the problems, you can resume the build with the command
2025-08-01T13:52:44.3603891Z [ERROR]   mvn <args> -rf :quarkus-gradle-model
2025-08-01T13:52:44.3800154Z [INFO] Found unpublished build scan 1754056364343-e29b8d10-5a8c-4fe8-a540-2690d95d3c2a
2025-08-01T13:52:44.6360902Z ##[error]Process completed with exit code 1.
```

**Comment by Eng-Fouad** [comment]
It is caused by using removed APIs in Gradle 9:

```
 error: constructor DefaultProjectDependency in class DefaultProjectDependency cannot be applied to given types;
                new DefaultProjectDependency((ProjectInternal) project, true, taskDependencyFactory));
                ^
  required: ProjectState
  found:    ProjectInternal,boolean,TaskDependencyFactory
  reason: actual and formal argument lists differ in length
```
```
error: cannot find symbol
        return resolvedArtifacts.size() < configuration.getFiles().size()
                                                       ^
  symbol:   method getFiles()
  location: variable configuration of type ResolvedConfiguration
2 errors
2 warnings
```

**Comment by Eng-Fouad** [comment]
cc @aloubyansky

**Review by gsmet — COMMENTED** [review]
I don't think we need all the tests but it would be nice to have a couple of sanity checks that we don't break Gradle 8.x for users in the coming months.

**Comment by Eng-Fouad** [comment]
> I don't think we need all the tests but it would be nice to have a couple of sanity checks that we don't break Gradle 8.x for users in the coming months.

I don't think I know how to write such tests. Is there an example? Or maybe leave to the experts @aloubyansky :)

BTW, as an example of breaking changes in Gradle, Quarkus 24.0 had a breaking change which uses new APIs introduced in Gradle 8.11. Some users report that they use Gradle 7.6.4 and it is no longer work on Quarkus 24.0: https://github.com/quarkusio/quarkus/issues/48829

However, I don't think we introduce any breaking changes with the latest changes and Quarkus should work with Gradle 8.11+.

**Comment by gsmet** [comment]
I think the idea would be to take a few simple tests from `integration-tests/gradle` and copy them in a new separate module.

That being said, we need to decide which version we want as the default for 3.26/3.27.

**Comment by aloubyansky** [comment]
> > I don't think we need all the tests but it would be nice to have a couple of sanity checks that we don't break Gradle 8.x for users in the coming months.
> 
> I don't think I know how to write such tests. Is there an example? Or maybe leave to the experts @aloubyansky :)

Once we find some experts, we'll definitely ask for their opinion!

> BTW, as an example of breaking changes in Gradle, Quarkus 24.0 had a breaking change which uses new APIs introduced in Gradle 8.11. Some users report that they use Gradle 7.6.4 and it is no longer work on Quarkus 24.0: #48829

That's a good point. AFAIR, that user was OK upgrading to Gradle 8? So, unless we fix it, we have Gradle 8 and 9 to test.

**Comment by aloubyansky** [comment]
@Eng-Fouad i rebased your branch and pushed another commit on top to enable a test run with Gradle 8.14 for a selected test. We may need to select some more.
Does this look OK to you?

**Comment by Eng-Fouad** [comment]
> @Eng-Fouad i rebased your branch and pushed another commit on top to enable a test run with Gradle 8.14 for a selected test. We may need to select some more.
> Does this look OK to you?

LGTM. Thanks.

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
@Eng-Fouad thanks for all your efforts on this one!
