### ISSUE TITLE
Class Not Found org/graalvm/polyglot/Value 1.4.1

### ISSUE THREAD

**Issue by abdallah-rashwan** [quarkusio/quarkus#41306]
### Describe the bug

Using Karate for int testing, getting the below error when trying to run tests using `  <dependency>
            <groupId>com.intuit.karate</groupId>
            <artifactId>karate-junit5</artifactId>
            <scope>test</scope>
        </dependency>`. The `Value` class is missing.

`java.lang.NoClassDefFoundError: org/graalvm/polyglot/Value
       at com.intuit.karate.core.Variable.<init>(Variable.java:72)
	at com.intuit.karate.core.Variable.<clinit>(Variable.java:66)
	at com.intuit.karate.core.Config.<init>(Config.java:94)
	at com.intuit.karate.core.ScenarioCall.getParentConfig(ScenarioCall.java:67)
	at com.intuit.karate.core.ScenarioRuntime.<init>(ScenarioRuntime.java:74)
	at com.intuit.karate.core.ScenarioIterator.tryAdvance(ScenarioIterator.java:162)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:292)
	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206)
	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:161)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:298)
	at java.base/java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
	at com.intuit.karate.junit5.FeatureNode.hasNext(FeatureNode.java:63)
	at com.intuit.karate.junit5.Karate.iterator(Karate.java:65)
	at java.base/java.lang.Iterable.spliterator(Iterable.java:101)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)`

I managed to overcome this by adding `graal-sdk 22.3.3` manually to be compatible with Truffle.

found this 
`<dependency>
        <groupId>org.graalvm.sdk</groupId>
        <artifactId>graal-sdk</artifactId>
        <version>23.1.2</version>
        <exclusions>
          <exclusion>
            <groupId>org.graalvm.polyglot</groupId>
            <artifactId>polyglot</artifactId>
          </exclusion>
        </exclusions>
      </dependency>` in "quarkus-bom-3.10.2.pom", might be useful.

### How to Reproduce?

1. Quarkus version 3.10.2
2. `com.intuit.karate karate-junit5-1.4.1`

**Comment by jamailun** [comment]
Same issue here, with Quarkus `3.11.2`.

**Comment by gsmet** [comment]
A small Maven reproducer might help.

**Comment by jamailun** [comment]
## How to reproduce

Ok, so that's what I found.I don't expect any real answer : I'm just writting my search :)
Here's the project holding a small demo: https://github.com/jamailun/karate-quarkus.
It **will** work on Quarkus `3.8.2` : the demo feature will run properly.

### Step 1: upgrade Quarkus to `3.8.3+`

From the version 3.8.3 (and commit [#39442](https://github.com/quarkusio/quarkus/pull/39442)) sdk-graal has been excluded.
So when launching the test, we obtain a :
`java.lang.NoClassDefFoundError: org/graalvm/polyglot/Value`


### Step 2 : Add `sdk-graal` _(you can skip this one)_

By adding the graal-sdk (and decommenting the block on line 69 of my demo), you'll have a new exception:
`ServiceConfiguration org.graalvm.polyglot.impl.AbstractPolyglotImpl: com.oracle.truffle.polyglot.PolyglotImpl not a subtype`. 
Same for previous versions.


### Step 3 : Add a only the most recent Graal's polyglot dependency

I discovered that from `23.1.0` onward, developpers should [import Graal SDK differently](https://github.com/oracle/graal/blob/master/sdk/CHANGELOG.md#version-2310).
By recommenting the previous block and importing only the `org.graalvm.polyglot.polyglot:24.0.1` (decomment block line 77 on my pom.xml) now everything will compile... but the tests won't be found. Even with debug mode, Karate just doesn't find the `.feature` anymore.
`FooUnitTests.testAllUnitTests no features or scenarios found: [classpath:org/jamailun]`


## Need help

And now I don't really know where to look. We'd like to keep our karate tests (we do have a lot of them) so any help would be gladly received.

**Comment by jamailun** [comment]
Bump ?

**Comment by francoisvandenplas** [comment]
Hello,
same issue here, with Quarkus 3.13.2.

**Comment by jamailun** [comment]
Bump again.

**Comment by jamailun** [comment]
@Lmbwilly I've checked it with latest release of Quarkus. Now, we don't have errors but Karate cannot find any tests.

I've updated my [reproducer](https://github.com/jamailun/karate-quarkus).

Just to insist : the tests do work well with Quarkus 3.8.2 and Karate 1.4.1.

**Comment by Lmbwilly** [comment]
@jamailun I've checked your reproducer and I only changed the call of the runner to `return Karate.run("classpath:org/jamailun/00.hello-world.feature");` and then it worked.
And I know with 3.8.2 all worked fine, I had the same problem as you.

**Comment by geoand** [comment]
I am going to close this as we didn't get feedback.

If this issue persists, please speak up and we can reopen it.
