### ISSUE TITLE
mvn clean quarkus:dev not working in mixed Kotlin project

### ISSUE THREAD

**Issue by kdubb** [quarkusio/quarkus#6931]
**Describe the bug**
Project with mixed Java/Kotlin doesn't compile after moving to `quarkus-maven-plugin:1.2.0.Final`.  Either the Kotlin compiler isn't running at all or it it is not running before Java (as required).

Switching the plugin version back to `1.1.1.Final` the project builds/runs correctly again.

**Expected behavior**
Using mixed Java/Kotlin with Quarkus builds correctly.

**Actual behavior**
Java source files cannot find symbols defined in Kotlin source files and produces compilation errors.

**To Reproduce**
1.  Create a mixed Java/Kotlin project built with Maven.
2. Reference a symbol defined in a Kotlin file from a Java file.
3. Build (e.g. using `package`) or run (e.g. using `quarks:dev`).

**Configuration**
N/A

**Screenshots**
N/A

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
   Darwin ... 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64
 - Output of `java -version`:
   java version "11.0.6" 2020-01-14 LTS
   Java(TM) SE Runtime Environment 18.9 (build 11.0.6+8-LTS)
   Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.6+8-LTS, mixed mode)
 - Output of `java -version`: 
N/A
 - GraalVM version (if different from Java): 
N/A
 - Quarkus version or git rev: 
`1.2.0.Final`

**Additional context**
N/A

**Comment by geoand** [comment]
Do you perhaps have a project that reproduces this difference between 1.1.1Final and 1.2.0.Final?

**Comment by kdubb** [comment]
@geoand https://github.com/kdubb/quarkus-kotlin-mixed-test Almost straight from the project generator. Fails with `1.2.0.Final` plugin but works with `1.1.1.Final`.

**Comment by geoand** [comment]
I reproduced this, but I changed the title to better reflect what actually happens.

The problem only occurs when `quarkus:dev` is not preceeded by `compile`.

**Comment by geoand** [comment]
To fix this we would need to also take the kotlin-maven-plugin into account in `DevMojo` when a compilation is detected.
However it's not straightforward since it seems some setup is needed otherwise we get:

```
Caused by: org.codehaus.plexus.component.repository.exception.ComponentLookupException: java.util.NoSuchElementException
      role: org.jetbrains.kotlin.maven.KotlinMavenPluginExtension
  roleHint: all-open
    at org.codehaus.plexus.DefaultPlexusContainer.lookup (DefaultPlexusContainer.java:267)
    at org.codehaus.plexus.DefaultPlexusContainer.lookup (DefaultPlexusContainer.java:255)
    at org.jetbrains.kotlin.maven.KotlinCompileMojoBase.loadCompilerPlugins (KotlinCompileMojoBase.java:321)
    at org.jetbrains.kotlin.maven.KotlinCompileMojoBase.getCompilerPluginOptions (KotlinCompileMojoBase.java:349)
    at org.jetbrains.kotlin.maven.KotlinCompileMojoBase.configureCompilerArguments (KotlinCompileMojoBase.java:489)
    at org.jetbrains.kotlin.maven.KotlinCompileMojoBase.execute (KotlinCompileMojoBase.java:215)
    at org.jetbrains.kotlin.maven.K2JVMCompileMojo.execute (K2JVMCompileMojo.java:222)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.twdata.maven.mojoexecutor.MojoExecutor.executeMojo (MojoExecutor.java:119)
    at io.quarkus.maven.DevMojo.executeCompileGoal (DevMojo.java:369)
```

**Comment by geoand** [comment]
#6953 should take care of the issue
