### ISSUE TITLE
Spring Data API Extension not working with Interface-based Projections

### ISSUE THREAD

**Issue by Michael-AT-Corporation** [quarkusio/quarkus#31774]
### Describe the bug

I want to use a Interface-based Projection in my repository. But when i try to compile it get the following error that the methods don't exist in the class. Even though they exist. In Spring this works as expected. Also when i ave multiple levels of generic repository interfaces and the generic type extends a base Class it also throws an exception. I added a comment in the reproducer how to create the error, it is in the interface ItemBaseRepository.

```posh
2023-03-10 21:47:19,719 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.spring.data.deployment.SpringDataJPAProcessor#build threw an exception: java.lang.IllegalArgumentException: getSymbolicImage method does not exists in at.atc.database.entities.Item class.
	at io.quarkus.spring.data.deployment.generate.DerivedMethodsAdder.generateCustomResultTypes(DerivedMethodsAdder.java:348)
	at io.quarkus.spring.data.deployment.generate.DerivedMethodsAdder.add(DerivedMethodsAdder.java:285)
	at io.quarkus.spring.data.deployment.generate.SpringDataRepositoryCreator.implementCrudRepository(SpringDataRepositoryCreator.java:117)
	at io.quarkus.spring.data.deployment.SpringDataJPAProcessor.implementCrudRepositories(SpringDataJPAProcessor.java:264)
	at io.quarkus.spring.data.deployment.SpringDataJPAProcessor.build(SpringDataJPAProcessor.java:129)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:1589)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:335)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:252)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:60)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:86)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:447)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:59)
	at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:149)
	at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:104)
	at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:131)
	at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:62)
```

### Expected behavior

I think right now the extension might only be picking up the functions from the first class, not inluding those from its super classes.

### How to Reproduce?

[QuarkusSpringDataInterfaceBasedProjections.zip](https://github.com/quarkusio/quarkus/files/10950974/QuarkusSpringDataInterfaceBasedProjections.zip)

### Output of `java -version`

Java version: 17.0.1

### Quarkus version or git rev

3.0.0.Aplha5

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
Java version: 17.0.1, vendor: Oracle Corporation
Default locale: de_AT, platform encoding: windows-1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by geoand** [comment]
Thanks for reporting.

https://github.com/quarkusio/quarkus/pull/31810 should take care of it

**Comment by Michael-AT-Corporation** [comment]
What would be the easiest way for me to test this fix? :)

**Comment by geoand** [comment]
I tested it with your reproducer and it worked.

For you to test it, you need to build the PR locally and use version `999-SNAPSHOT` of Quarkus, while also using `io.quarkus` as the artifactId of the BOM

**Comment by Michael-AT-Corporation** [comment]
Her I am again :)
I tried it out with 3.0.1.Final and it works when the methods are in the same class as the entity. But if the field and so the method for the interface projection is in the superclass (MappedSuperclass) i still get the error that the method does not exist.
This is the new reproducer:
[reproducerJPAInterfaceMapping.zip](https://github.com/quarkusio/quarkus/files/11359598/reproducerJPAInterfaceMapping.zip)

**Comment by geoand** [comment]
Understood, thanks for reporting!

**Comment by Michael-AT-Corporation** [comment]
The reproducer is working with 3.0.4.Final. But when the query returns a value i still get the excpetion that the method does not exists. I suppose this might happen when it is trying to convert it to the given interface.
To reproduce just save a Parent before you call the method `findByIdAndName`.
Like:
`parentRepository.save(Parent.builder().id(1L).name("Test").build());` then
`parentRepository.findByIdAndName(1L,"Test");`

**Comment by geoand** [comment]
I tried the steps above and it worked for me so I must be missing something.

Mind attaching an updated sample?

**Comment by Michael-AT-Corporation** [comment]
Sure. 
i can call `getParent` as many times as I want and it works. But after i called `createParent` i always get the exception that the method does not exist:
`java.lang.NoSuchMethodError: 'java.lang.String at.atc.database.entities.Parent.getId()'
        at at.atc.database.repository.SmallParent_1708b88140835c48cf8606fb2deb050670db060d.convert_findByIdAndName(Unknown Source)`
[reproducerJPAInterfaceMapping-3.0.4.zip](https://github.com/quarkusio/quarkus/files/11590738/reproducerJPAInterfaceMapping-3.0.4.zip)

**Comment by geoand** [comment]
Your latest sample fails for me because while `Parent#getId` returns `Long`, `SmallParent#getId` returns `String`.

**Comment by Michael-AT-Corporation** [comment]
Yeah sorry, that was my fault. It works just fine. 
Thanks for the fix. :)

**Comment by geoand** [comment]
NP!

**Comment by Michael-AT-Corporation** [comment]
I am experiencing some strange behaviour.
When i start my application everythign works fine but when i have a live reload because i edited some other code then suddenly the function is no longer found.
`java.lang.NoSuchMethodError: 'at.atc.database.repository.interfaces.LicenseOrderLevy_66ba1cee66b0e8307b249a09826d9143aba8bac3 at.atc.database.repository.interfaces.LicenseOrderLevy_66ba1cee66b0e8307b249a09826d9143aba8bac3.convert_findOrderLevyByRestaurantId(at.atc.database.entities.License)'`
Even when i do a complete restart it might not be found. I have no idea why this is happening. Hopefully you have some kind of an idea what it could be. If not thanks anyways.
Unfortunately i don't seem to be able to get this kind of behaviour with the reproducer from this issue.

**Comment by geoand** [comment]
> Hopefully you have some kind of an idea what it could be

When I initially read this, I did have an idea about why it might happen, but looking at the source code I see that we are not making the mistake I thought we were, so unfortunately I am out of ideas...
If you do however come up with a reproducer, then I'd be glad to take another look.

**Comment by Michael-AT-Corporation** [comment]
Now it also can happen when i build a jar.
I got this reproducer. 
Steps toreproduce:

1. Call `createParent` in `ParentResource`
2. Call `getParent` or `getParent`
3. If no error happens chnage something in your code (i changed the output from the System.out.println) so that the dev mode reloads your application and got to step 2. It can take some tries to get the error (normally not longer than 5 to 10 tries) but hopefully the error appears.

[Uploading reproducerJPAInterfaceMapping.zip…]()

**Comment by geoand** [comment]
Although I was to reproduce this initially, when I started debugging, I stopped being able to :(

**Comment by Michael-AT-Corporation** [comment]
At least you were able to reproduce it :)
It might have something to do with `ParentRepository1` and `ParentRepository2`. When I remove `ParentRepository2` I don't seem to get the exception (even after severeal reloads). But after I readded it, the exception starts happing again after about one to about 5 reloads. (All in dev mode reload, no restarts)

**Comment by geoand** [comment]
Yeah, it's weird....

**Comment by geoand** [comment]
Do you mind creating a new issue for this so we can track it separately (as it is something different from the original issue)

**Comment by Michael-AT-Corporation** [comment]
Sure
