### PR TITLE
Bump CRaC to 1.5.0

### LINKED ISSUE #48501: Quarkus uses io.github.crac:org-crac:0.1.3 instead of the latest org.crac:crac:1.5.0
### Describe the bug

After upgrading Quarkus from `3.21.4` to upper version, I noticed that `@QuarkusTest` fails with a `NoSuchMethodError` related to `QuarkusClassLoader.setStartupAction` when the project includes `org.crac:crac:1.5.0`. Removing this dependency resolves the issue, as Quarkus appears to use `io.github.crac:org-crac:0.1.3` instead of the latest official `org.crac:crac:1.5.0`.
This version mismatch can cause runtime errors and classpath conflicts. It would be beneficial if Quarkus could use or support the latest `org.crac:crac` artifact to ensure compatibility and avoid such issues.

### Expected behavior

Quarkus should use the latest stable version of the CRaC API (`org.crac:crac:1.5.0`) when available, or provide a clear and consistent mechanism for integrating with the official CRaC library. Including or updating to the latest CRaC dependency should not cause runtime errors, classpath conflicts, or incompatibilities with Quarkus features such as `@QuarkusTest`. All core Quarkus functionality and extensions should work seamlessly when the latest CRaC API is present in the project.

### Actual behavior

When including the latest official CRaC library (`org.crac:crac:1.5.0`) in a Quarkus project, Quarkus still uses its own dependency on `io.github.crac:org-crac:0.1.3`. This results in classpath conflicts and incompatibilities, causing runtime errors such as `NoSuchMethodError` during test execution or application startup. Removing the newer `org.crac:crac:1.5.0` dependency resolves the issue, but prevents the use of the latest CRaC features and bug fixes.

### How to Reproduce?

add org.crac:crac:1.5.0 as dependecy

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

21

### Quarkus version or git rev

3.23.4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvn

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by alex-martel**
- Closes: https://github.com/quarkusio/quarkus/issues/48501

### CODE REVIEW

**Review by gsmet — APPROVED** [review]

**Comment by geoand** [comment]
The CI failures are very suspicious and I am wondering if they are caused by https://github.com/quarkusio/quarkus/pull/48614. 

WDYT @gsmet ?
