### ISSUE TITLE
org.testcontainers dependencies exists in quarkus-universe-bom

### ISSUE THREAD

**Issue by juangon** [quarkusio/quarkus#9968]
**Describe the bug**
It seems that it isn't possible to upgrade org.testcontainers:mariadb or other container dependencies to 1.14.3 in a custom project.

Workaround is to explicitely add root org.test.container dependency in pom.xml

**Expected behavior**
No errors when using any container `getJdbcUrl()` method after upgrading org.testcontainers:mariadb to 1.14.3

**Actual behavior**
Error while executing tests are thrown: 
```
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
Caused by: java.lang.reflect.InvocationTargetException
Caused by: java.lang.NoSuchMethodError: java.lang.String org.testcontainers.containers.MariaDBContainer.getHost()
 ```

**To Reproduce**
1. Add org.testcontainers:mariadb:1.14.3 as a test dependency in pom.xml
2. Add MariaDBContainer (or any other one) in a class extending QuarkusTestResourceLifecycleManager
3. Add needed code to start/stop container in the previously created DB resource class, and return  `container.getJdbcUrl()` in overriden `start` method as `quarkus.datasource.jdbc.url` property.
4. Start tests.

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 5.3.0-51-generic #44~18.04.2-Ubuntu
 - Output of `java -version`: openjdk version &quot;11.0.7
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.5.1.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 

**Additional context**
(Add any other context about the problem here.)

**Comment by gsmet** [comment]
@juangon could you prepare a simple reproducer? Thanks.

**Comment by geoand** [comment]
I thought we removed it...

**Comment by famod** [comment]
I can confirm that there are various testcontainers entries in the universe BOM: https://repo1.maven.org/maven2/io/quarkus/quarkus-universe-bom/1.5.2.Final/quarkus-universe-bom-1.5.2.Final.pom

I had a litte "fun" with https://github.com/quarkusio/quarkus-platform/blob/master/bom/runtime/pom.xml and I was able to narrow it down. The following listing shows which BOM is dragging in which testcontainers dependency:
```
quarkus-hazelcast-client-bom:

        <groupId>org.testcontainers</groupId>
        <artifactId>testcontainers</artifactId>
        <version>1.12.4</version>

        <groupId>org.testcontainers</groupId>
        <artifactId>junit-jupiter</artifactId>
        <version>1.12.4</version>

        <groupId>org.testcontainers</groupId>
        <artifactId>postgresql</artifactId>
        <version>1.12.4</version>

kogito-bom:

        <groupId>org.testcontainers</groupId>
        <artifactId>testcontainers</artifactId>
        <version>1.12.4</version>

        <groupId>org.testcontainers</groupId>
        <artifactId>kafka</artifactId>
        <version>1.12.4</version>

cassandra-quarkus-bom:

        <groupId>org.testcontainers</groupId>
        <artifactId>cassandra</artifactId>
        <version>1.12.4</version>
```
I am not sure whether the `cassandra` bit is problematic since it doesn't pull in the main testcontainers artifact.

And now another "fun" part: https://issues.apache.org/jira/browse/MNG-5600
Meaning no exclusions for BOM imports and that means (AFAICS) that testcontainers has to be removed from the respective upstream BOMs.

**Comment by geoand** [comment]
`testcontainers` won't be removed from the BOM as we rely on it for [DevServices](https://github.com/quarkusio/quarkus/pull/14960)
