### ISSUE TITLE
QuarkusTest in 1.3.0.Alpha1 requires JUnit 5.6?

### ISSUE THREAD

**Issue by sdaschner** [quarkusio/quarkus#7020]
**Description**

It seems that switching to Quarkus `1.3.0` (Alpha1) requires JUnit Jupiter `5.6.0`, or, at least running a `@QuarkusTest` with Jupiter `5.5.2` fails with:

```
java.lang.NoSuchMethodError: org/junit/jupiter/api/extension/InvocationInterceptor$Invocation.skip()V (loaded from file:/home/sebastian/.m2/repository/org/junit/jupiter/junit-jupiter-api/5.5.2/junit-jupiter-api-5.5.2.jar by jdk.internal.loader.ClassLoaders$AppClassLoader@61b0d555) called from class io.quarkus.test.junit.QuarkusTestExtension (loaded from file:/home/sebastian/.m2/repository/io/quarkus/quarkus-junit5/1.3.0.Alpha1/quarkus-junit5-1.3.0.Alpha1.jar by jdk.internal.loader.ClassLoaders$AppClassLoader@61b0d555).
```

For me, that's not a show-stopper since I can update to JUnit `5.6.0`, but is there a way to resolve it? If not, then we might add a documentation that folks need to update their JUnit5. This worked in Quarkus `1.2.0.Final`.

**Comment by gsmet** [comment]
Yes. We specifically worked with the JUnit team to fix some issues that were blocking our class loader work.

What surprises me is that it's in our BOM:
```
            <dependency>
                <groupId>org.junit</groupId>
                <artifactId>junit-bom</artifactId>
                <version>${junit.jupiter.version}</version>
                <scope>import</scope>
                <type>pom</type>
            </dependency>
```
so if you don't specify a version, everything should be fine. Do you specify the version manually?

**Comment by gsmet** [comment]
I added a note here: https://github.com/quarkusio/quarkus/wiki/Migration-Guide-1.3 .

**Comment by sdaschner** [comment]
Thanks!

> Do you specify the version manually?
Yes, and some projects do, so I think the note is helpful :)

**Comment by gsmet** [comment]
> Yes, and some projects do, so I think the note is helpful :)

Sure, thanks for reporting it!
