### PR TITLE
Fix compilation error

### PR DESCRIPTION
**Pull request by gastaldi**
This fixes the error introduced by https://github.com/quarkusio/quarkus/commit/8f439467bb504112a0b34f3f377d690d9ecb872c

### CODE REVIEW

**Review by geoand — APPROVED** [review]
Works for me, thanks!

File: independent-projects/tools/common/src/main/java/io/quarkus/generators/rest/BasicRestProjectGenerator.java [hunk 1]
```diff
@@ -171,10 +171,10 @@ private void createReadme() throws IOException {
             BuildTool buildTool = getBuildTool();
             switch (buildTool) {
                 case MAVEN:
-                    generate("templates/README.maven.ftl", context, readme, "read me");
```
Comment (stuartwdouglas) [inline independent-projects/tools/common/src/main/java/io/quarkus/generators/rest/BasicRestProjectGenerator.java]: Will this whitespace change break the formatter?

Comment (gastaldi) [reply independent-projects/tools/common/src/main/java/io/quarkus/generators/rest/BasicRestProjectGenerator.java]: I ran the full build before submitting, so I guess it won't

**Review by machi1990 — APPROVED** [review]

File: independent-projects/tools/common/src/main/java/io/quarkus/generators/rest/BasicRestProjectGenerator.java (hunk 1 above)
Comment (stuartwdouglas) [reply independent-projects/tools/common/src/main/java/io/quarkus/generators/rest/BasicRestProjectGenerator.java]: Apparently not because it is in independent-projects

Comment (geoand) [reply independent-projects/tools/common/src/main/java/io/quarkus/generators/rest/BasicRestProjectGenerator.java]: I executed a sample `mvn clean install` and the source wasn't changed so I guess the formatter didn't have any issues
