### ISSUE TITLE
Banned dependency breaks Apache poi-ooxml >= 5.3.0

### ISSUE THREAD

**Issue by ninelore** [quarkusio/quarkus#42500]
### Describe the bug

Apache poi-ooxml throws NoSuchMethodExceptions at runtime because an older version of commons-io is used than required. I believe this to be related to and/or caused by #30542 and/or #30723

### Expected behavior

commons-io 2.16.1 being downloaded by maven and used 

### Actual behavior

commons-io 2.15.1 is being downloaded despite the only package requiring it wanting 2.16.1, leading to following Exception
(some class names and packages have been anonymized)
```
2024-08-13 10:22:10,698 ERROR [org.jbo.thr.errors] (executor-thread-3) Thread Thread[executor-thread-3,5,main] threw an uncaught exception: java.lang.NoSuchMethodError: 'org.apache.commons.io.input.BoundedInputStream$Builder org.apache.commons.io.input.BoundedInputStream.builder()'
        at org.apache.poi.util.IOUtils.peekFirstNBytes(IOUtils.java:145)
        at org.apache.poi.poifs.filesystem.FileMagic.valueOf(FileMagic.java:209)
        at org.apache.poi.openxml4j.opc.internal.ZipHelper.verifyZipHeader(ZipHelper.java:145)
        at org.apache.poi.openxml4j.opc.internal.ZipHelper.openZipFile(ZipHelper.java:217)
        at org.apache.poi.openxml4j.opc.ZipPackage.<init>(ZipPackage.java:188)
        at org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:285)
        at foo.bar.businessLogic.transferToCSV(BusinessClass.java:217)
        at foo.bar.businessLogic.startThread(BusinessClass.java:122)
        at foo.bar.businessLogic_ClientProxy.startThread(Unknown Source)
        at foo.bar.rest.TriggerService.lambda$doBusinessLogic$0(TriggerService.java:87)
        at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1512)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Unknown Source)
```

### How to Reproduce?

Will add later

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.22631.3880]

### Output of `java -version`

openjdk version "21.0.4" 2024-07-16 LTS

### Quarkus version or git rev

3.8.5

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.7 (8b094c9513efc1b9ce2d952b3b9c8eaedaf8cbf0)

### Additional information

https://mvnrepository.com/artifact/org.apache.poi/poi-ooxml/5.3.0
![image](https://github.com/user-attachments/assets/ade632ea-9405-4e81-b3f1-0fbe4afe15dd)
```
$ mvn dependency:tree
[INFO] Scanning for projects...
[INFO] 
[INFO] ---------------------< foo.bar:business-application >---------------------
[INFO] Building business-application 1.0-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- dependency:3.6.1:tree (default-cli) @ business-application ---
[INFO] foo.bar:business-application:jar:1.0-SNAPSHOT
[INFO] +- io.quarkus:quarkus-jdbc-mysql:jar:3.8.5:compile
[INFO] |  +- io.quarkus:quarkus-arc:jar:3.8.5:compile
[INFO] |  |  +- io.quarkus.arc:arc:jar:3.8.5:compile
[INFO] |  |  |  \- io.smallrye.reactive:mutiny:jar:2.5.8:compile
[INFO] |  |  \- org.eclipse.microprofile.context-propagation:microprofile-context-propagation-api:jar:1.3:compile
[INFO] |  \- com.mysql:mysql-connector-j:jar:8.3.0:compile
[INFO] +- io.quarkus:quarkus-hibernate-orm:jar:3.8.5:compile
[INFO] |  +- io.quarkus:quarkus-core:jar:3.8.5:compile
[INFO] |  |  +- jakarta.annotation:jakarta.annotation-api:jar:2.1.1:compile
[INFO] |  |  +- jakarta.enterprise:jakarta.enterprise.cdi-api:jar:4.0.1:compile
[INFO] |  |  |  +- jakarta.enterprise:jakarta.enterprise.lang-model:jar:4.0.1:compile
[INFO] |  |  |  \- jakarta.interceptor:jakarta.interceptor-api:jar:2.1.0:compile
[INFO] |  |  +- jakarta.inject:jakarta.inject-api:jar:2.0.1:compile
[INFO] |  |  +- io.smallrye.common:smallrye-common-os:jar:2.2.0:compile
[INFO] |  |  +- io.quarkus:quarkus-ide-launcher:jar:3.8.5:compile
[INFO] |  |  +- io.quarkus:quarkus-development-mode-spi:jar:3.8.5:compile
[INFO] |  |  +- io.smallrye.config:smallrye-config:jar:3.5.4:compile
[INFO] |  |  |  \- io.smallrye.config:smallrye-config-core:jar:3.5.4:compile
[INFO] |  |  |     +- io.smallrye.common:smallrye-common-classloader:jar:2.2.0:compile
[INFO] |  |  |     \- io.smallrye.config:smallrye-config-common:jar:3.5.4:compile
[INFO] |  |  +- org.jboss.logging:jboss-logging:jar:3.5.3.Final:compile
[INFO] |  |  +- org.jboss.logmanager:jboss-logmanager:jar:3.0.4.Final:compile
[INFO] |  |  |  +- io.smallrye.common:smallrye-common-constraint:jar:2.2.0:compile
[INFO] |  |  |  +- io.smallrye.common:smallrye-common-cpu:jar:2.2.0:compile
[INFO] |  |  |  +- io.smallrye.common:smallrye-common-expression:jar:2.2.0:compile
[INFO] |  |  |  |  \- io.smallrye.common:smallrye-common-function:jar:2.2.0:compile
[INFO] |  |  |  +- io.smallrye.common:smallrye-common-net:jar:2.2.0:compile
[INFO] |  |  |  \- io.smallrye.common:smallrye-common-ref:jar:2.2.0:compile
[INFO] |  |  +- org.jboss.logging:jboss-logging-annotations:jar:2.2.1.Final:compile
[INFO] |  |  +- org.jboss.threads:jboss-threads:jar:3.5.1.Final:compile
[INFO] |  |  +- org.wildfly.common:wildfly-common:jar:1.7.0.Final:compile
[INFO] |  |  +- io.quarkus:quarkus-bootstrap-runner:jar:3.8.5:compile
[INFO] |  |  |  \- io.smallrye.common:smallrye-common-io:jar:2.2.0:compile
[INFO] |  |  \- io.quarkus:quarkus-fs-util:jar:0.0.10:compile
[INFO] |  +- io.quarkus:quarkus-agroal:jar:3.8.5:compile
[INFO] |  |  +- io.quarkus:quarkus-datasource:jar:3.8.5:compile
[INFO] |  |  +- io.agroal:agroal-api:jar:2.3:compile
[INFO] |  |  +- io.agroal:agroal-narayana:jar:2.3:compile
[INFO] |  |  |  \- org.jboss:jboss-transaction-spi:jar:8.0.0.Final:compile
[INFO] |  |  +- io.agroal:agroal-pool:jar:2.3:compile
[INFO] |  |  \- io.quarkus:quarkus-credentials:jar:3.8.5:compile
[INFO] |  +- io.quarkus:quarkus-narayana-jta:jar:3.8.5:compile
[INFO] |  |  +- io.quarkus:quarkus-transaction-annotations:jar:3.8.5:compile
[INFO] |  |  +- io.quarkus:quarkus-mutiny:jar:3.8.5:compile
[INFO] |  |  |  +- io.quarkus:quarkus-smallrye-context-propagation:jar:3.8.5:compile
[INFO] |  |  |  |  \- io.smallrye:smallrye-context-propagation:jar:2.1.0:compile
[INFO] |  |  |  |     +- io.smallrye:smallrye-context-propagation-api:jar:2.1.0:compile
[INFO] |  |  |  |     \- io.smallrye:smallrye-context-propagation-storage:jar:2.1.0:compile
[INFO] |  |  |  \- io.smallrye.reactive:mutiny-smallrye-context-propagation:jar:2.5.8:compile
[INFO] |  |  +- io.quarkus:quarkus-datasource-common:jar:3.8.5:compile
[INFO] |  |  +- io.smallrye:smallrye-context-propagation-jta:jar:2.1.0:compile
[INFO] |  |  +- io.smallrye.reactive:smallrye-reactive-converter-api:jar:3.0.1:compile
[INFO] |  |  |  \- org.reactivestreams:reactive-streams:jar:1.0.4:compile
[INFO] |  |  +- io.smallrye.reactive:smallrye-reactive-converter-mutiny:jar:3.0.1:compile
[INFO] |  |  +- io.smallrye.reactive:mutiny-zero-flow-adapters:jar:1.0.0:compile
[INFO] |  |  +- org.jboss.narayana.jta:narayana-jta:jar:7.0.0.Final:compile
[INFO] |  |  |  +- jakarta.resource:jakarta.resource-api:jar:2.1.0:compile
[INFO] |  |  |  +- org.jboss.invocation:jboss-invocation:jar:2.0.0.Final:compile
[INFO] |  |  |  \- org.eclipse.microprofile.reactive-streams-operators:microprofile-reactive-streams-operators-api:jar:3.0:compile
[INFO] |  |  \- org.jboss.narayana.jts:narayana-jts-integration:jar:7.0.0.Final:compile
[INFO] |  +- org.hibernate.orm:hibernate-core:jar:6.4.8.Final:compile
[INFO] |  |  +- com.fasterxml:classmate:jar:1.6.0:runtime
[INFO] |  |  \- org.antlr:antlr4-runtime:jar:4.13.0:runtime
[INFO] |  +- net.bytebuddy:byte-buddy:jar:1.14.11:compile
[INFO] |  +- org.hibernate.common:hibernate-commons-annotations:jar:6.0.6.Final:compile
[INFO] |  +- org.hibernate.orm:hibernate-graalvm:jar:6.4.8.Final:compile
[INFO] |  +- org.glassfish.jaxb:jaxb-runtime:jar:4.0.4:compile
[INFO] |  |  \- org.glassfish.jaxb:jaxb-core:jar:4.0.4:compile
[INFO] |  |     +- org.eclipse.angus:angus-activation:jar:2.0.1:compile
[INFO] |  |     +- org.glassfish.jaxb:txw2:jar:4.0.4:compile
[INFO] |  |     \- com.sun.istack:istack-commons-runtime:jar:4.1.2:compile
[INFO] |  +- jakarta.xml.bind:jakarta.xml.bind-api:jar:4.0.1:compile
[INFO] |  |  \- jakarta.activation:jakarta.activation-api:jar:2.1.2:compile
[INFO] |  +- jakarta.persistence:jakarta.persistence-api:jar:3.1.0:compile
[INFO] |  +- jakarta.transaction:jakarta.transaction-api:jar:2.0.1:compile
[INFO] |  +- org.hibernate:quarkus-local-cache:jar:0.3.0:compile
[INFO] |  \- io.quarkus:quarkus-caffeine:jar:3.8.5:compile
[INFO] |     \- com.github.ben-manes.caffeine:caffeine:jar:3.1.5:compile
[INFO] |        \- com.google.errorprone:error_prone_annotations:jar:2.24.0:compile
[INFO] +- io.quarkus:quarkus-resteasy:jar:3.8.5:compile
[INFO] |  +- io.quarkus:quarkus-vertx-http:jar:3.8.5:compile
[INFO] |  |  +- io.quarkus:quarkus-security-runtime-spi:jar:3.8.5:compile
[INFO] |  |  +- io.smallrye.common:smallrye-common-vertx-context:jar:2.2.0:compile
[INFO] |  |  +- io.quarkus.security:quarkus-security:jar:2.0.3.Final:compile
[INFO] |  |  +- io.smallrye.reactive:smallrye-mutiny-vertx-web:jar:3.11.0:compile
[INFO] |  |  |  +- io.smallrye.reactive:smallrye-mutiny-vertx-web-common:jar:3.11.0:compile
[INFO] |  |  |  +- io.smallrye.reactive:smallrye-mutiny-vertx-auth-common:jar:3.11.0:compile
[INFO] |  |  |  +- io.smallrye.reactive:smallrye-mutiny-vertx-bridge-common:jar:3.11.0:compile
[INFO] |  |  |  \- io.smallrye.reactive:smallrye-mutiny-vertx-uri-template:jar:3.11.0:compile
[INFO] |  |  |     \- io.vertx:vertx-uri-template:jar:4.5.7:compile
[INFO] |  |  +- io.vertx:vertx-web:jar:4.5.7:compile
[INFO] |  |  |  +- io.vertx:vertx-web-common:jar:4.5.7:compile
[INFO] |  |  |  +- io.vertx:vertx-auth-common:jar:4.5.7:compile
[INFO] |  |  |  \- io.vertx:vertx-bridge-common:jar:4.5.7:compile
[INFO] |  |  \- io.github.crac:org-crac:jar:0.1.3:compile
[INFO] |  \- io.quarkus:quarkus-resteasy-server-common:jar:3.8.5:compile
[INFO] |     +- io.quarkus:quarkus-resteasy-common:jar:3.8.5:compile
[INFO] |     |  +- org.jboss.resteasy:resteasy-core:jar:6.2.7.Final:compile
[INFO] |     |  |  \- com.ibm.async:asyncutil:jar:0.1.0:compile
[INFO] |     |  +- jakarta.ws.rs:jakarta.ws.rs-api:jar:3.1.0:compile
[INFO] |     |  \- org.jboss.resteasy.microprofile:microprofile-config:jar:2.1.5.Final:compile
[INFO] |     |     \- jakarta.servlet:jakarta.servlet-api:jar:6.0.0:compile
[INFO] |     +- org.jboss.resteasy:resteasy-cdi:jar:6.2.7.Final:compile
[INFO] |     |  \- org.jboss.resteasy:resteasy-core-spi:jar:6.2.7.Final:compile
[INFO] |     \- jakarta.validation:jakarta.validation-api:jar:3.0.2:compile
[INFO] +- io.quarkus:quarkus-resteasy-jackson:jar:3.8.5:compile
[INFO] |  +- io.quarkus:quarkus-jackson:jar:3.8.5:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.17.0:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:jar:2.17.0:compile
[INFO] |  |  \- com.fasterxml.jackson.module:jackson-module-parameter-names:jar:2.17.0:compile
[INFO] |  \- org.jboss.resteasy:resteasy-jackson2-provider:jar:6.2.7.Final:compile
[INFO] |     +- com.fasterxml.jackson.core:jackson-core:jar:2.17.0:compile
[INFO] |     +- com.fasterxml.jackson.core:jackson-annotations:jar:2.17.0:compile
[INFO] |     +- com.fasterxml.jackson.jakarta.rs:jackson-jakarta-rs-base:jar:2.17.0:compile
[INFO] |     +- com.fasterxml.jackson.jakarta.rs:jackson-jakarta-rs-json-provider:jar:2.17.0:compile
[INFO] |     +- com.fasterxml.jackson.module:jackson-module-jakarta-xmlbind-annotations:jar:2.17.0:compile
[INFO] |     \- com.github.java-json-tools:json-patch:jar:1.13:compile
[INFO] |        +- com.github.java-json-tools:msg-simple:jar:1.2:compile
[INFO] |        |  \- com.github.java-json-tools:btf:jar:1.3:compile
[INFO] |        \- com.github.java-json-tools:jackson-coreutils:jar:2.0:compile
[INFO] +- io.quarkus:quarkus-smallrye-openapi:jar:3.8.5:compile
[INFO] |  +- io.smallrye:smallrye-open-api-core:jar:3.10.0:compile
[INFO] |  |  +- org.eclipse.microprofile.openapi:microprofile-openapi-api:jar:3.1.1:compile
[INFO] |  |  +- org.eclipse.microprofile.config:microprofile-config-api:jar:3.0.3:compile
[INFO] |  |  +- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.17.0:compile
[INFO] |  |  |  \- org.yaml:snakeyaml:jar:2.2:compile
[INFO] |  |  \- io.smallrye:jandex:jar:3.1.6:compile
[INFO] |  \- io.quarkus:quarkus-swagger-ui:jar:3.8.5:compile
[INFO] +- io.quarkus:quarkus-smallrye-health:jar:3.8.5:compile
[INFO] |  +- io.smallrye:smallrye-health:jar:4.1.0:compile
[INFO] |  |  +- org.eclipse.microprofile.health:microprofile-health-api:jar:4.0.1:compile
[INFO] |  |  +- io.smallrye:smallrye-health-api:jar:4.1.0:compile
[INFO] |  |  \- jakarta.json:jakarta.json-api:jar:2.1.3:compile
[INFO] |  +- io.smallrye:smallrye-health-provided-checks:jar:4.1.0:compile
[INFO] |  \- io.quarkus:quarkus-jsonp:jar:3.8.5:compile
[INFO] |     \- org.eclipse.parsson:parsson:jar:1.1.5:compile
[INFO] +- io.quarkus:quarkus-micrometer-registry-prometheus:jar:3.8.5:compile
[INFO] |  +- io.quarkus:quarkus-micrometer:jar:3.8.5:compile
[INFO] |  |  \- io.micrometer:micrometer-core:jar:1.12.2:compile
[INFO] |  |     +- io.micrometer:micrometer-commons:jar:1.12.2:compile
[INFO] |  |     +- io.micrometer:micrometer-observation:jar:1.12.2:compile
[INFO] |  |     +- org.hdrhistogram:HdrHistogram:jar:2.1.12:runtime
[INFO] |  |     \- org.latencyutils:LatencyUtils:jar:2.0.3:runtime
[INFO] |  \- io.micrometer:micrometer-registry-prometheus:jar:1.12.2:compile
[INFO] |     \- io.prometheus:simpleclient_common:jar:0.16.0:compile
[INFO] |        \- io.prometheus:simpleclient:jar:0.16.0:compile
[INFO] |           +- io.prometheus:simpleclient_tracer_otel:jar:0.16.0:compile
[INFO] |           |  \- io.prometheus:simpleclient_tracer_common:jar:0.16.0:compile
[INFO] |           \- io.prometheus:simpleclient_tracer_otel_agent:jar:0.16.0:compile
[INFO] +- io.quarkus:quarkus-scheduler:jar:3.8.5:compile
[INFO] |  +- io.quarkus:quarkus-scheduler-kotlin:jar:3.8.5:compile
[INFO] |  |  \- io.quarkus:quarkus-scheduler-common:jar:3.8.5:compile
[INFO] |  |     +- io.quarkus:quarkus-scheduler-api:jar:3.8.5:compile
[INFO] |  |     +- io.quarkus:quarkus-scheduler-spi:jar:3.8.5:compile
[INFO] |  |     +- io.opentelemetry.instrumentation:opentelemetry-instrumentation-api:jar:1.32.0:compile
[INFO] |  |     |  +- io.opentelemetry:opentelemetry-api:jar:1.32.0:compile
[INFO] |  |     |  |  \- io.opentelemetry:opentelemetry-context:jar:1.32.0:compile
[INFO] |  |     |  \- io.opentelemetry:opentelemetry-extension-incubator:jar:1.32.0-alpha:runtime
[INFO] |  |     \- com.cronutils:cron-utils:jar:9.2.1:compile
[INFO] |  +- io.quarkus:quarkus-virtual-threads:jar:3.8.5:compile
[INFO] |  |  \- io.vertx:vertx-core:jar:4.5.7:compile
[INFO] |  |     +- io.netty:netty-common:jar:4.1.108.Final:compile
[INFO] |  |     +- io.netty:netty-buffer:jar:4.1.108.Final:compile
[INFO] |  |     +- io.netty:netty-transport:jar:4.1.108.Final:compile
[INFO] |  |     +- io.netty:netty-handler:jar:4.1.108.Final:compile
[INFO] |  |     |  \- io.netty:netty-transport-native-unix-common:jar:4.1.108.Final:compile
[INFO] |  |     +- io.netty:netty-handler-proxy:jar:4.1.108.Final:compile
[INFO] |  |     |  \- io.netty:netty-codec-socks:jar:4.1.108.Final:compile
[INFO] |  |     +- io.netty:netty-codec-http:jar:4.1.108.Final:compile
[INFO] |  |     +- io.netty:netty-codec-http2:jar:4.1.108.Final:compile
[INFO] |  |     +- io.netty:netty-resolver:jar:4.1.108.Final:compile
[INFO] |  |     \- io.netty:netty-resolver-dns:jar:4.1.108.Final:compile
[INFO] |  |        \- io.netty:netty-codec-dns:jar:4.1.108.Final:compile
[INFO] |  +- io.quarkus:quarkus-vertx:jar:3.8.5:compile
[INFO] |  |  +- io.quarkus:quarkus-netty:jar:3.8.5:compile
[INFO] |  |  |  +- io.netty:netty-codec:jar:4.1.108.Final:compile
[INFO] |  |  |  \- com.aayushatharva.brotli4j:brotli4j:jar:1.16.0:compile
[INFO] |  |  |     +- com.aayushatharva.brotli4j:service:jar:1.16.0:compile
[INFO] |  |  |     \- com.aayushatharva.brotli4j:native-windows-x86_64:jar:1.16.0:compile
[INFO] |  |  +- io.netty:netty-codec-haproxy:jar:4.1.108.Final:compile
[INFO] |  |  +- io.smallrye.common:smallrye-common-annotation:jar:2.2.0:compile
[INFO] |  |  +- io.quarkus:quarkus-vertx-latebound-mdc-provider:jar:3.8.5:compile
[INFO] |  |  +- io.smallrye.reactive:smallrye-mutiny-vertx-core:jar:3.11.0:compile
[INFO] |  |  |  +- io.smallrye.reactive:smallrye-mutiny-vertx-runtime:jar:3.11.0:compile
[INFO] |  |  |  \- io.smallrye.reactive:vertx-mutiny-generator:jar:3.11.0:compile
[INFO] |  |  |     \- io.vertx:vertx-codegen:jar:4.5.7:compile
[INFO] |  |  \- io.smallrye:smallrye-fault-tolerance-vertx:jar:6.2.6:compile
[INFO] |  +- org.jboss.slf4j:slf4j-jboss-logmanager:jar:2.0.0.Final:compile
[INFO] |  \- org.glassfish.expressly:expressly:jar:5.0.0:compile
[INFO] |     \- jakarta.el:jakarta.el-api:jar:5.0.1:compile
[INFO] +- io.github.openfeign:feign-jackson:jar:13.3:compile
[INFO] |  +- io.github.openfeign:feign-core:jar:13.3:compile
[INFO] |  \- com.fasterxml.jackson.core:jackson-databind:jar:2.17.0:compile
[INFO] +- org.apache.poi:poi-ooxml:jar:5.3.0:compile
[INFO] |  +- org.apache.poi:poi:jar:5.3.0:compile
[INFO] |  |  +- commons-codec:commons-codec:jar:1.16.1:compile
[INFO] |  |  +- org.apache.commons:commons-math3:jar:3.6.1:compile
[INFO] |  |  \- com.zaxxer:SparseBitSet:jar:1.3:compile
[INFO] |  +- org.apache.poi:poi-ooxml-lite:jar:5.3.0:compile
[INFO] |  +- org.apache.xmlbeans:xmlbeans:jar:5.2.1:compile
[INFO] |  +- org.apache.commons:commons-compress:jar:1.26.1:compile
[INFO] |  |  \- org.apache.commons:commons-lang3:jar:3.14.0:compile
[INFO] |  +- commons-io:commons-io:jar:2.15.1:compile     <----------------- Here 
[INFO] |  +- com.github.virtuald:curvesapi:jar:1.08:compile
[INFO] |  +- org.apache.logging.log4j:log4j-api:jar:2.22.1:compile
[INFO] |  \- org.apache.commons:commons-collections4:jar:4.4:compile
[INFO] +- com.rabbitmq:amqp-client:jar:5.21.0:compile
[INFO] |  \- org.slf4j:slf4j-api:jar:2.0.6:compile
[INFO] \- com.google.code.gson:gson:jar:2.10.1:compile
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.653 s
[INFO] Finished at: 2024-08-13T10:33:43+02:00
[INFO] ------------------------------------------------------------------------
```

**Comment by gsmet** [comment]
That's what the Quarkus BOM does: align the dependencies to what has been vetted for Quarkus to behave properly. Most of the time, it's for your benefit, and sometimes it doesn't align with what external dependencies might expect.

You will have to override the version in the POM of your app if you want to enforce a newer version.

**Comment by ninelore** [comment]
Thanks for the Info

**Comment by gsmet** [comment]
BTW, recent non-LTS versions use a much newer version (but they are not LTS).
