### PR TITLE
Hibernate ORM 7.1.0.CR2

### LINKED ISSUE #47353: Swapping Parent with Hibernate entity fails
### Describe the bug

I have a `Parent` and a child `Entity`. The Parent has the following relationship:
```
@OneToMany(orphanRemoval = true, cascade = CascadeType.ALL)
private List<Child> children;
```
Now I create two Parents: Parent A and Parent B where Parent A has one child.
Then i swap the Child from Parent A to B in one Transaction. This works fine.
But when i want to swap the Child back to Parent A I get a duplicate key error like:
```
2025-04-14 17:51:38,683 ERROR [org.hib.eng.jdb.spi.SqlExceptionHelper] (main) (conn=12) Duplicate entry '1' for key 'UKqflmxmtp7l47kj96gtnijqty4'
```
I don't know what the core issue is but i also tested it with spring boot and there it works fine. Maybe it has something to do with the bytecode enhancement, but i have no idea.

### Expected behavior

Swapping back to the original Parent should work.

### Actual behavior

_No response_

### How to Reproduce?

[QuarkusJpaTestParentSwap.zip](https://github.com/user-attachments/files/19738935/QuarkusJpaTestParentSwap.zip)
For the database to retain the values during the tests you need to activate `testcontainers.reuse.enable=true`.
In `ParentDtoResourcesTest` i have written som tests.

1. Start `initialiseDb`
2. Start `swapParentAToParentB`
3. Start `swapParentBToParentA`
Now you should get the following error:
```
2025-04-14 17:51:38,683 ERROR [org.hib.eng.jdb.spi.SqlExceptionHelper] (main) (conn=12) Duplicate entry '1' for key 'UKqflmxmtp7l47kj96gtnijqty4'
```

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

3.21.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Sanne**
I'm taking over from Yoann as he's on PTO, so continuing his work based on preview PR #49140 

* Fixes #49132 
* Fixes #47353  

Migration guide entry:

```
== Hibernate ORM

=== Upgrade to Hibernate ORM 7.1

The Quarkus extension for Hibernate ORM was upgraded to Hibernate ORM 7.1.

Hibernate ORM 7.1 is for the most part backwards-compatible with Hibernate ORM 7.0. However, a few breaking changes are to be expected. Below are the ones most likely to affect existing applications.

Refer to the https://docs.jboss.org/hibernate/orm/7.1/migration-guide/migration-guide.html[Hibernate ORM 7.1 migration guide] for more information.

=== API changes

* https://docs.jboss.org/hibernate/orm/7.1/migration-guide/migration-guide.html#lock-options[A few of the more problematic, deprecated features of `LockOptions` have been removed].
* https://docs.jboss.org/hibernate/orm/7.1/migration-guide/migration-guide.html#session-getLobHelper[`Session#getLobHelper` was deprecated in favor of `Hibernate#getLobHelper`].

[[orm-db-versions]]
=== Minimum database versions

As with every new version of Hibernate ORM, the minimum required version of databases was bumped to the *oldest version still supported* by their respective vendor. In particular:

* IBM DB2: bumped minimum version from 10.5 to 11.1
* MariaDB: bumped minimum version from 10.5 to 10.6
* Microsoft SQL Server: bumped minimum version from 11.0 (2012) to 12.0 (2014)

See https://docs.jboss.org/hibernate/orm/7.1/dialect/dialect.html[here] for details on the current minimum versions.

== Hibernate Reactive

=== Upgrade to Hibernate Reactive 3.1

The Quarkus extension for Hibernate Reactive was upgraded to Hibernate Reactive 3.1.

Hibernate Reactive 3.1 is backwards-compatible with Hibernate Reactive 3.0, with the exception of a few breaking changes inherited from Hibernate ORM and listed xref:#++hibernate-orm++[above].

== Hibernate Search

=== Upgrade to Hibernate Search 8.1

The Quarkus extensions for Hibernate Search were upgraded to Hibernate Search 8.1.

Hibernate Search 8.1 is backwards-compatible with Hibernate Search 8.0, apart from a few deprecations.

Refer to the the https://docs.jboss.org/hibernate/search/8.1/migration/html_single/[Hibernate Search 8.1 migration guide] for more information.

```

### CODE REVIEW

**Review by lucamolteni — APPROVED** [review]

**Comment by Sanne** [comment]
Converting to draft after meeting with the ORM team: there's currently some doubt about the date of the ORM Final release, it might need to slip a little.

**Comment by Sanne** [comment]
Updated to Hibernate ORM 7.1.0.CR2, Reactive 3.1.0.CR2, Search 8.1.0.CR2

**Comment by mbellade** [comment]
Hey @Sanne, looks like we need to implement the new `find(String, Object)` method introduced by https://github.com/hibernate/hibernate-orm/commit/ae00af96fac962686d2a6764a62201903fea2943

**Comment by yrodiere** [comment]
Looks like one of our tests using a custom H2 dialect needs to be adjusted following the mutation strategy changes:

```
Compilation failure:
/home/runner/_work/quarkus/quarkus/extensions/hibernate-orm/deployment/src/test/java/io/quarkus/hibernate/orm/dev/H2CustomDialect.java:[20,52] error: <anonymous io.quarkus.hibernate.orm.dev.H2CustomDialect$1> is not abstract and does not override abstract method buildHandler(org.hibernate.query.sqm.tree.SqmDeleteOrUpdateStatement<?>,org.hibernate.query.sqm.internal.DomainParameterXref,org.hibernate.query.spi.DomainQueryExecutionContext) in org.hibernate.query.sqm.mutation.spi.SqmMultiTableMutationStrategy
        return new SqmMultiTableMutationStrategy() {
```

**Comment by yrodiere** [comment]
Also, thank you for taking care of this :)

**Comment by Sanne** [comment]
> Also, thank you for taking care of this :)

don't you worry!

**Review by gsmet — APPROVED** [review]
Let's unblock the other PRs!

**Comment by yrodiere** [comment]
> Migration guide entry:

Added to https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.26
