### ISSUE TITLE
Quarkus with latest io.kubernetes:client-java throws java.lang.NoClassDefFoundError: com/google/protobuf/RuntimeVersion$RuntimeDomain

### ISSUE THREAD

**Issue by sdyga** [quarkusio/quarkus#41511]
### Describe the bug

**When I upgraded io.kubernetes:client-java from 20.0.1 to 21.0.0 
this code (simplified for this ticket) started to raise exception**

```java
package com.company;

import io.kubernetes.client.proto.V1Admission;
import io.quarkus.test.junit.QuarkusTest;
import org.junit.jupiter.api.Test;

@QuarkusTest
public class AdmissionTest {

    @Test
    void test(){
        V1Admission.AdmissionReview.newBuilder()
                .setResponse(V1Admission.AdmissionResponse.newBuilder()
                        .setAllowed(true)
                        .setUid("123456789")
                        .build())
                .build();
    }
}
```

**An exception:**
```
com/google/protobuf/RuntimeVersion$RuntimeDomain
java.lang.NoClassDefFoundError: com/google/protobuf/RuntimeVersion$RuntimeDomain
	at io.kubernetes.client.proto.V1Admission$AdmissionReview.<clinit>(V1Admission.java:6801)
	at com.company.AdmissionTest.test(AdmissionTest.java:12)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:1017)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestMethod(QuarkusTestExtension.java:831)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.ClassNotFoundException: com.google.protobuf.RuntimeVersion$RuntimeDomain
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:526)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:476)
	... 7 more
```

### Expected behavior

No exception

### Actual behavior

Exception it raised.

### How to Reproduce?

1. Create new project
2. Add gradle dependencies
    implementation 'io.kubernetes:client-java:21.0.0'
    implementation 'io.kubernetes:client-java-extended:21.0.0'
3. Execute test:
```java
@Test
    void test(){
        V1Admission.AdmissionReview.newBuilder()
                .setResponse(V1Admission.AdmissionResponse.newBuilder()
                        .setAllowed(true)
                        .setUid("123456789")
                        .build())
                .build();
    }
```

### Output of `uname -a` or `ver`

MINGW64_NT-10.0-19044

### Output of `java -version`

openjdk 17.0.4 2022-07-19

### Quarkus version or git rev

3.12.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.7-20240301012057+0000

### Additional information

**Reason:**
**io.kubernetes:client-java:21.0.0** was compiled with **com.google.protobuf:protobuf-java:4.27.1** where com/google/protobuf/RuntimeVersion$RuntimeDomain is present. 

Quarkus uses **com.google.protobuf:protobuf-java:3.25.0** without this class. Can I upgrade this library in my project?

**Comment by geoand** [comment]
cc @manusa

**Comment by manusa** [comment]
> cc @manusa

Note that the user is using the [_official_ Kubernetes Client](https://github.com/kubernetes-client/java) provided by the CNCF and not the one and only [Fabric8 Kubernetes Client](https://github.com/fabric8io/kubernetes-client).

It looks like some convergence dependency issues for both projects.

**Comment by geoand** [comment]
Ah, nice catch @manusa! 

I am going to close this then since this is not a Quarkus issue (it's a typical Maven dependency mismatch issue)

**Comment by sdyga** [comment]
So what is the proposed solution? Switch to [Fabric8 Kubernetes Client](https://github.com/fabric8io/kubernetes-client) ?
Or I could try to enforce usage of com.google.protobuf:protobuf-java:4.27.1 together with Quarkus 3.12.0?

**Comment by geoand** [comment]
> Or I could try to enforce usage of com.google.protobuf:protobuf-java:4.27.1 together with Quarkus 3.12.0?

You can try and enforce whatever version of protobuf the client needs, but there is no guarantee that other things that need it will continue to work.
