### ISSUE TITLE
NoSuchMethodError with @Decorator since Quarkus 2.8

### ISSUE THREAD

**Issue by simongun** [quarkusio/quarkus#28398]
### Describe the bug

While working correctly with Quarkus <= 2.7.x, since 2.8 and up to 2.13 a NoSuchMethodError is thrown for something that is Decorated with a Decorator implementation that is parametized.

### Expected behavior

For the provided JUnit test not to fail, and implementation class to be correctly decorated.

### Actual behavior

NoSuchMethodError in decorator.

### Output of `java -version`

11

### GraalVM version (if different from Java)

n/a

### Quarkus version or git rev

2.8 - 2.13

**Comment by gsmet** [comment]
Could you provide a reproducer? Thanks.

**Comment by simongun** [comment]
[](url)
[reproducer.zip](https://github.com/quarkusio/quarkus/files/9715087/reproducer.zip)

Simple run mvn package. You will see it reports the error. Then switch back in pom to quarkus version 2.7.6, where this will run successfully.

**Comment by mkouba** [comment]
This looks like a duplicate of https://github.com/quarkusio/quarkus/issues/24624.

We should probably at least detect this case and report a reasonable error.

**Comment by geoand** [comment]
Indeed! I'll close as a duplicate
