### ISSUE TITLE
Quarkus 3.31.2 tests fail with LinkageError between build-time (QuarkusClassLoader) and app loader for Gizmo/Jandex; 3.29.x is OK

### ISSUE THREAD

**Issue by troymal** [quarkusio/quarkus#52540]
#### Summary
- After upgrading to Quarkus 3.31.x (3.31.2), a Quarkus test fails during augmentation with a classloader/linkage error involving Gizmo and Jandex. The same module/tests work on 3.29.x.
- We unified our BOMs and verified that only one Gizmo (`io.quarkus.gizmo:gizmo:1.10.1`) is present, as pulled by `quarkus-core-deployment:3.31.2` both in compile-time augmentation and in the test stack, yet the failure persists.
- Attempts to fix via `quarkus.class-loading.parent-first-artifacts` helped clarify the issue but did not resolve it. Using `removed-artifacts` for ASM caused `NoClassDefFoundError` and was rolled back.

#### Environment
- Java: 21
- Quarkus: 3.31.2 (works on 3.29.x; fails on 3.31.x)
- Maven project with multiple modules; failing module: `exp-frontend/exp-frontend-service`
- OS: macOS (developer machine)

#### What fails
- Failing test class: `BffSseTest` (but failure happens before test body executes — during Quarkus test app startup/augmentation)

#### Primary error (current)
```
Caused by: java.lang.LinkageError: loader constraint violation: when resolving method 'java.lang.String io.quarkus.gizmo.DescriptorUtils.typeToString(org.jboss.jandex.Type)'
 the class loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @49b07ee3 of the current class, io/quarkus/vertx/http/deployment/HttpSecurityProcessor, 
 and the class loader 'app' for the method's defining class, io/quarkus/gizmo/DescriptorUtils, have different Class objects for the type org/jboss/jandex/Type used in the signature
 (io.quarkus.vertx.http.deployment.HttpSecurityProcessor is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @49b07ee3, parent loader 'app';
  io.quarkus.gizmo.DescriptorUtils is in unnamed module of loader 'app')
```
- Interpretation: `HttpSecurityProcessor` (build-time, QuarkusClassLoader) calls a Gizmo method whose signature includes `org.jboss.jandex.Type`, but `DescriptorUtils` is loaded from the app loader, and the `Type` in the signature is from a different loader. This causes a loader constraint violation.

#### Earlier related error observed during the same attempts
```
Caused by: java.lang.ClassCastException: class io.quarkus.arc.processor.BeanGenerator$1 cannot be cast to class io.quarkus.gizmo.MethodCreator
 (io.quarkus.arc.processor.BeanGenerator$1 and io.quarkus.gizmo.MethodCreator are in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @...)
```
- Also suggests a mismatch between how Gizmo (and related classes) are loaded in augmentation vs app/test classpath.

#### One-time side-effect error when we tried to “remove” ASM (rolled back)
```
Caused by: java.lang.NoClassDefFoundError: org/objectweb/asm/ClassVisitor
  at io.smallrye.config.ConfigMappingInterface.getClassBytes(ConfigMappingInterface.java:193)
Caused by: java.lang.ClassNotFoundException: org.objectweb.asm.ClassVisitor
  at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:552)
```
- This happened only when we experimented with `quarkus.class-loading.removed-artifacts` for ASM. We removed that setting afterward.

#### What we verified (dependency trees)
Gizmo presence (test path):
```
example:exp-frontend-service:jar:2.0.3-SNAPSHOT
\- io.quarkus:quarkus-junit:jar:3.31.2:test
   \- io.quarkus:quarkus-test-common:jar:3.31.2:test
      \- io.quarkus:quarkus-core-deployment:jar:3.31.2:test
         \- io.quarkus.gizmo:gizmo:jar:1.10.1:test
```
Fuller slice (all 3.31.2 on our side):
```
example:exp-frontend-service:jar:2.0.3-SNAPSHOT
+- ...
+- io.quarkus:quarkus-arc:jar:3.31.2:compile
+- io.quarkus:quarkus-rest:jar:3.31.2:compile
+- io.quarkus:quarkus-vertx-http:jar:3.31.2:compile
+- io.quarkus:quarkus-smallrye-openapi:jar:3.31.2:compile
+- io.quarkus:quarkus-junit:jar:3.31.2:test
|  \- io.quarkus:quarkus-test-common:jar:3.31.2:test
|     \- io.quarkus:quarkus-core-deployment:jar:3.31.2:test
|        \- io.quarkus.gizmo:gizmo:jar:1.10.1:test
\- io.quarkus:quarkus-jacoco:jar:3.31.2:test
```
- We unified BOMs so that all Quarkus artifacts are 3.31.2. The custom extension we use (`com.example.quarkus:example-security-quarkus`) was updated to align with 3.31.2 as well.

#### Attempts already made
- Ensured a single Gizmo version: `io.quarkus.gizmo:gizmo:1.10.1` (as pulled by Quarkus 3.31.2).
- Verified no direct app dependency on Gizmo or Jandex (they only come transitively via Quarkus build-time/test artifacts).
- Cleaned local Maven cache for all related artifacts (Gizmo, Jandex, Quarkus core/arc/deployment) and rebuilt with `-U`.
- Added classloading settings (tried both main `application.properties` and then dedicated test `src/test/resources/application.properties`):
  - `quarkus.class-loading.parent-first-artifacts=io.quarkus.gizmo:gizmo,org.jboss:jandex,org.ow2.asm:asm,org.ow2.asm:asm-util,org.ow2.asm:asm-analysis`
  - Added classloading DEBUG logs to see what’s being loaded from which loader.
- We also briefly tried `quarkus.class-loading.removed-artifacts` for ASM/Jandex/Gizmo to prevent app-side presence, but that caused `NoClassDefFoundError` for ASM during config mapping codegen, so we rolled that back.

#### How to reproduce (from our project)
- Command we run to reproduce (only this module):
```
mvn -U -f exp-frontend/pom.xml -pl exp-frontend-service -Dtest=BffSseTest test
```
- On Quarkus 3.29.x the same test setup works; on 3.31.2 it fails with the `LinkageError` above before the test body starts.

#### What we expected vs what we see
- Expected: Quarkus test app should start; augmentation should succeed without classloader/linkage issues; Gizmo/Jandex should be consistently resolved for build-time processors and app/test classpath.
- Actual: Augmentation fails with `LinkageError` due to `HttpSecurityProcessor` (QuarkusClassLoader) and `DescriptorUtils` (app loader) disagreeing on the `org.jboss.jandex.Type` in the method signature.

#### Questions for the Quarkus team
1) Is there a known change in 3.31.x test/augmentation classloading that can yield a split between build-time and app loaders for Gizmo/Jandex (compared to 3.29.x)?
2) Is the `quarkus.class-loading.parent-first-artifacts` approach sufficient in 3.31.x to keep Gizmo/Jandex/ASM consistent, or is there a recommended alternative to avoid this loader split during tests?
3) Could `io.quarkus.vertx.http.deployment.HttpSecurityProcessor` be invoking Gizmo methods under circumstances where the app loader might take precedence for Gizmo/Jandex, leading to the signature type mismatch?
4) Any guidance on a canonical way to ensure Gizmo/Jandex are loaded from the same loader as Quarkus build-time processors during tests on 3.31.x?

#### Notes
- We also see a SmallRye OpenAPI warning:
```
SROAP07903: Duplicate operationId: getIaCompensation ... and ... getIaCompensations ...
```
This seems unrelated to the failure (a warning), included for completeness.

#### Willing to provide a reproducer
- We can try to extract a minimal reproducer, but due to the multi-module setup and custom extension presence, it might take time. If there’s an existing reproducer pattern for 3.31.x classloading issues in tests, we’re happy to adapt ours.

Thanks a lot for any pointers or known workarounds. Happy to run with `-X`, provide detailed classload logs (`-Xlog:class+load=info`), or tweak settings to isolate the exact trigger.

### Output of `uname -a` or `ver`

Darwin Kernel Version 25.2.0: Tue Nov 18 21:09:56 PST 2025; root:xnu-12377.61.12~1/RELEASE_ARM64_T6041 arm64

### Output of `java -version`

OpenJDK 64-Bit Server VM Temurin-21.0.8+9 (build 21.0.8+9-LTS, mixed mode, sharing)

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.12 (848fbb4bf2d427b72bdb2471c22fced7ebd9a7a1)

**Comment by gsmet** [comment]
So I would remove all the attempts you did to fix the issue and would very carefully check all the dependencies are aligned, because it looks very odd.
There were some class loader changes, but I wouldn't expect this sort of issues.

And this one is extremely odd:

> Caused by: java.lang.ClassCastException: class io.quarkus.arc.processor.BeanGenerator$1 cannot be cast to class io.quarkus.gizmo.MethodCreator
 (io.quarkus.arc.processor.BeanGenerator$1 and io.quarkus.gizmo.MethodCreator are in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @...)

Because this part of the code has been moved to Gizmo 2. So the package should be `io.quarkus.gizmo2` not `io.quarkus.gizmo`.

Use `mvn quarkus:dependency-tree -Dmode=dev` to get the full dependency tree.

**Comment by troymal** [comment]
Thanks for the hint. 
I ran the suggested command:
```
mvn quarkus:dependency-tree -Dmode=dev
```
Relevant part shows both Gizmo 1.x and 2.x on the test path via `quarkus-test-common` → `quarkus-core-deployment`:
```
[INFO] |  +- io.quarkus:quarkus-test-common:jar:3.31.2:test (version managed from 3.31.2)
[INFO] |  |  +- io.quarkus:quarkus-core-deployment:jar:3.31.2:test (version managed from 3.31.2)
[INFO] |  |  |  +- (io.quarkus:quarkus-classloader-commons:jar:3.31.2:test - version managed from 3.31.2; omitted for duplicate)
[INFO] |  |  |  +- org.aesh:readline:jar:2.6:test (version managed from 2.6)
[INFO] |  |  |  |  \- org.fusesource.jansi:jansi:jar:2.4.0:test (version managed from 2.4.0)
[INFO] |  |  |  +- org.aesh:aesh:jar:2.8.2:test (version managed from 2.8.2)
[INFO] |  |  |  |  \- (org.aesh:readline:jar:2.6:test - version managed from 2.6; omitted for duplicate)
[INFO] |  |  |  +- (org.apache.commons:commons-lang3:jar:3.20.0:test - version managed from 3.20.0; omitted for duplicate)
[INFO] |  |  |  +- org.apache.commons:commons-compress:jar:1.28.0:test (version managed from 1.28.0)
[INFO] |  |  |  |  +- (commons-codec:commons-codec:jar:1.20.0:test - version managed from 1.19.0; omitted for duplicate)
[INFO] |  |  |  |  +- (commons-io:commons-io:jar:2.21.0:test - version managed from 2.20.0; omitted for duplicate)
[INFO] |  |  |  |  \- (org.apache.commons:commons-lang3:jar:3.20.0:test - version managed from 3.18.0; omitted for duplicate)
[INFO] |  |  |  +- (org.wildfly.common:wildfly-common:jar:2.0.1:test - version managed from 2.0.1; omitted for duplicate)
[INFO] |  |  |  +- io.quarkus.gizmo:gizmo:jar:1.10.1:test (version managed from 1.10.1)
[INFO] |  |  |  |  +- (org.ow2.asm:asm:jar:9.9.1:test - version managed from 9.9.1; omitted for duplicate)
[INFO] |  |  |  |  +- org.ow2.asm:asm-util:jar:9.9.1:test (version managed from 9.9.1)
[INFO] |  |  |  |  |  +- (org.ow2.asm:asm:jar:9.9.1:test - version managed from 9.9.1; omitted for duplicate)
[INFO] |  |  |  |  |  +- (org.ow2.asm:asm-tree:jar:9.9.1:test - version managed from 9.9.1; omitted for duplicate)
[INFO] |  |  |  |  |  \- org.ow2.asm:asm-analysis:jar:9.9.1:test (version managed from 9.9.1)
[INFO] |  |  |  |  |     \- (org.ow2.asm:asm-tree:jar:9.9.1:test - version managed from 9.9.1; omitted for duplicate)
[INFO] |  |  |  |  \- (io.smallrye:jandex:jar:3.5.3:test - version managed from 3.5.3; omitted for duplicate)
[INFO] |  |  |  +- io.quarkus.gizmo:gizmo2:jar:2.0.0:test (version managed from 2.0.0)
[INFO] |  |  |  |  +- io.smallrye.classfile:jdk-classfile-backport:jar:26.cr1:test
[INFO] |  |  |  |  +- (io.smallrye.common:smallrye-common-constraint:jar:2.15.0:test - version managed from 2.14.0; omitted for duplicate)
[INFO] |  |  |  |  \- io.smallrye.common:smallrye-common-resource:jar:2.15.0:test (version managed from 2.14.0)
[INFO] |  |  |  |     \- (io.smallrye.common:smallrye-common-constraint:jar:2.15.0:test - version managed from 2.15.0; omitted for duplicate)
[INFO] |  |  |  +- (io.smallrye:jandex:jar:3.5.3:test - version managed from 3.5.3; omitted for duplicate)
[INFO] |  |  |  +- io.smallrye:jandex-gizmo2:jar:3.5.3:test (version managed from 3.5.3)
[INFO] |  |  |  |  +- (io.smallrye:jandex:jar:3.5.3:test - version managed from 3.5.3; omitted for duplicate)
[INFO] |  |  |  |  \- (io.quarkus.gizmo:gizmo2:jar:2.0.0:test - version managed from 2.0.0.Beta10; omitted for duplicate)
```
We still get the augmentation failure with loader split in the signature:
```
LinkageError: ... io.quarkus.gizmo.DescriptorUtils.typeToString(org.jboss.jandex.Type)
HttpSecurityProcessor (QuarkusClassLoader) vs DescriptorUtils (app loader)
```
Questions:
- Is it expected that both `gizmo` and `gizmo2` are present on 3.31.2 test path?
- What’s the recommended way to prevent loader split (so `DescriptorUtils` and `org.jboss.jandex.Type` come from the same loader) in tests?

**Comment by gsmet** [comment]
Can you do a | grep io.quarkus | grep -v 3.31.2 ?

And also check you don’t have two different quarkus-bom in your project?

You are enforcing the BOM in all modules right?

It’s expected to have both Gizmo 1 and 2. We are transitioning to the latter but it will take time.

**Comment by troymal** [comment]
We use a single Quarkus BOM managed via the parent POM (no second BOM imported).

I ran the grep commands, but the result seems right:
```
[INFO] |  |  \- io.quarkus:quarkus-fs-util:jar:1.3.0:compile (version managed from 1.3.0)
[INFO] |  |  |  \- (io.quarkus.security:quarkus-security:jar:2.3.2:compile - version managed from 2.3.2; omitted for duplicate)
[INFO] |  |  +- io.quarkus.security:quarkus-security:jar:2.3.2:compile (version managed from 2.3.2)
[INFO] |  |  +- (io.quarkus.security:quarkus-security:jar:2.3.2:compile - version managed from 2.3.2; omitted for duplicate)
[INFO] |  |  |  +- (io.quarkus:quarkus-fs-util:jar:1.3.0:test - version managed from 1.3.0; omitted for duplicate)
[INFO] |  |  |  +- io.quarkus.gizmo:gizmo:jar:1.10.1:test (version managed from 1.10.1)
[INFO] |  |  |  +- io.quarkus.gizmo:gizmo2:jar:2.0.0:test (version managed from 2.0.0)
[INFO] |  |  |  |  \- (io.quarkus.gizmo:gizmo2:jar:2.0.0:test - version managed from 2.0.0.Beta10; omitted for duplicate)
[INFO] |  |  |  +- (io.quarkus:quarkus-fs-util:jar:1.3.0:test - version managed from 1.3.0; omitted for duplicate)
```

**Comment by gsmet** [comment]
Ok. I think we will need a reproducer then.

**Comment by geoand** [comment]
As @gsmet says, we'll need a minimal reproducer that shows the problem in action so we can debug and see what's going on

**Comment by gsmet** [comment]
I will close this one as we didn’t get a reproducer. Feel free to reopen when you have one.

**Comment by dgaffuri** [comment]
Hi, hope this may help. I had a similar problem, that is the gizmo related exception in test execution after moving to 3.32, and I solved it updating the quarkiverse ironjacamar extension from 1.6.1 (built with 3.15.5) to 1.7.1 (built with 3.30.2)
