### ISSUE TITLE
Analyze EA JDK 17 failures

### ISSUE THREAD

**Issue by famod** [quarkusio/quarkus#18372]
## Description

Analyze failures, create upstream issues etc.

Current status:
- quarkus-hibernate-orm-panache-kotlin: `java.lang.NoSuchMethodError: 'void com.sun.tools.javac.util.Log.<init>(com.sun.tools.javac.util.Context, java.io.PrintWriter, java.io.PrintWriter, java.io.PrintWriter)' at org.jetbrains.kotlin.kapt3.base.javac.KaptJavaLog.<init>(KaptJavaLog.kt:30)`
  https://youtrack.jetbrains.com/issue/KT-47583
- quarkus-cli: ?
- quarkus-integration-test-devtools: ?
- quarkus-integration-test-scala: ?
- quarkus-integration-test-kotlin: ?
- quarkus-tck-microprofile-jwt: ?

See also: https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/EA.20build

**Comment by famod** [comment]
@sberyozkin @radcortez this might be something for you:
> - quarkus-tck-microprofile-jwt: one test fails with:
>  ```
>  2021-07-09T02:41:37.1778449Z FAILED: testFailAlgorithm
>  2021-07-09T02:41:37.1778964Z         Illustrate validation of iss
>  2021-07-09T02:41:37.1779535Z org.testng.TestException: 
>  2021-07-09T02:41:37.1781961Z Expected exception of type class org.jose4j.jwt.consumer.InvalidJwtException but got org.jose4j.lang.InvalidAlgorithmException: A128KW is an unknown, unsupported or unavailable alg algorithm (not one of [RSA1_5, RSA-OAEP, RSA-OAEP-256, dir, ECDH-ES, A128GCMKW, A192GCMKW, A256GCMKW]).
>  ```

I suppose Java 17 dropped that A128KW algorithm.

**Comment by famod** [comment]
New test failures added (Gradle Kotlin): `Could not initialize class org.jetbrains.kotlin.com.intellij.util.io.FileChannelUtil`

Those failures vanish when updating kotlin to 1.5.30, most likely due to https://youtrack.jetbrains.com/issue/KT-47152
