### ISSUE TITLE
Dev mode no more working due to Flyway after migrating to 1.4

### ISSUE THREAD

**Issue by loicmathieu** [quarkusio/quarkus#8908]
**Describe the bug**
After migrating my project to 1.4.1.Final (or current master) from 1.3.1.Final dev mode didn't work anymore due to Flyway config issue.

Building and running the jar works fine.

**Expected behavior**
`mvn clean quarkus:dev` works fine.

**Actual behavior**
`mvn clean quarkus:dev`  generates the following error and fails to start:

```
java.lang.NoClassDefFoundError: io/quarkus/runtime/generated/Config
	at io.quarkus.flyway.runtime.FlywayBuildTimeConfig_c42b0f573e7faeaed099a8367d785c3e78ab4b89_Synthetic_Bean.create(FlywayBuildTimeConfig_c42b0f573e7faeaed099a8367d785c3e78ab4b89_Synthetic_Bean.zig:137)
	at io.quarkus.flyway.runtime.FlywayBuildTimeConfig_c42b0f573e7faeaed099a8367d785c3e78ab4b89_Synthetic_Bean.get(FlywayBuildTimeConfig_c42b0f573e7faeaed099a8367d785c3e78ab4b89_Synthetic_Bean.zig:78)
	at io.quarkus.flyway.runtime.FlywayBuildTimeConfig_c42b0f573e7faeaed099a8367d785c3e78ab4b89_Synthetic_Bean.get(FlywayBuildTimeConfig_c42b0f573e7faeaed099a8367d785c3e78ab4b89_Synthetic_Bean.zig:184)
	at io.quarkus.arc.impl.CurrentInjectionPointProvider.get(CurrentInjectionPointProvider.java:53)
	at io.quarkus.flyway.runtime.FlywayProducer_Bean.create(FlywayProducer_Bean.zig:154)
	at io.quarkus.flyway.runtime.FlywayProducer_Bean.create(FlywayProducer_Bean.zig:35)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:79)
	at io.quarkus.arc.impl.ComputingCache$CacheFunction.lambda$apply$0(ComputingCache.java:99)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.getValue(ComputingCache.java:41)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:25)
	at io.quarkus.flyway.runtime.FlywayProducer_ClientProxy.arc$delegate(FlywayProducer_ClientProxy.zig:130)
	at io.quarkus.flyway.runtime.FlywayProducer_ClientProxy.arc_contextualInstance(FlywayProducer_ClientProxy.zig:148)
	at io.quarkus.flyway.runtime.FlywayProducer_ProducerMethod_produceFlyway_e096c4088c379ae0dbd3422e3804c8a9b56a720b_Bean.create(FlywayProducer_ProducerMethod_produceFlyway_e096c4088c379ae0dbd3422e3804c8a9b56a720b_Bean.zig:152)
	at io.quarkus.flyway.runtime.FlywayProducer_ProducerMethod_produceFlyway_e096c4088c379ae0dbd3422e3804c8a9b56a720b_Bean.get(FlywayProducer_ProducerMethod_produceFlyway_e096c4088c379ae0dbd3422e3804c8a9b56a720b_Bean.zig:73)
	at io.quarkus.flyway.runtime.FlywayProducer_ProducerMethod_produceFlyway_e096c4088c379ae0dbd3422e3804c8a9b56a720b_Bean.get(FlywayProducer_ProducerMethod_produceFlyway_e096c4088c379ae0dbd3422e3804c8a9b56a720b_Bean.zig:58)
	at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:380)
	at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:393)
	at io.quarkus.arc.impl.ArcContainerImpl$1.get(ArcContainerImpl.java:244)
	at io.quarkus.arc.impl.ArcContainerImpl$1.get(ArcContainerImpl.java:241)
	at io.quarkus.arc.runtime.ArcRecorder$2$1.create(ArcRecorder.java:84)
	at io.quarkus.arc.runtime.BeanContainer.instance(BeanContainer.java:19)
	at io.quarkus.flyway.runtime.FlywayRecorder.migrate(FlywayRecorder.java:45)
	at io.quarkus.flyway.runtime.FlywayRecorder.doStartActions(FlywayRecorder.java:28)
	at io.quarkus.deployment.steps.FlywayProcessor$configureRuntimeProperties-1733420004.deploy_0(FlywayProcessor$configureRuntimeProperties-1733420004.zig:64)
	at io.quarkus.deployment.steps.FlywayProcessor$configureRuntimeProperties-1733420004.deploy(FlywayProcessor$configureRuntimeProperties-1733420004.zig:83)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:267)
	at io.quarkus.runtime.Application.start(Application.java:89)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:90)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:61)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:106)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:99)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: io.quarkus.runtime.generated.Config
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:341)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:
```

**To Reproduce**
I was unable to reproduce it on a fresh project generated with the maven archetype.

This error occurs on a project with the following extensions: agroal, cdi, flyway, hibernate-orm, hibernate-orm-panache, hibernate-validator, jaeger, jdbc-postgresql, mutiny, narayana-jta, rest-client, resteasy, resteasy-jsonb, security, security-oauth2, security-properties-file, smallrye-context-propagation, smallrye-fault-tolerance, smallrye-health, smallrye-metrics, smallrye-openapi, smallrye-opentracing

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Linux 5.3.0-46-generic #38-Ubuntu SMP Fri Mar 27 17:37:05 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - Output of `java -version`: openjdk version "11.0.5" 2019-10-15
 - Quarkus version or git rev: 1.4.1.Final or current master
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)

**Comment by stuartwdouglas** [comment]
Should be fixed by https://github.com/quarkusio/quarkus/pull/8806

I did not realise the config bean changes had made it into 1.4, for some reason I thought they were in 1.5.

**Comment by loicmathieu** [comment]
Yes, #8806 fixed this.
