### ISSUE TITLE
legacy mysql5 driver throws java.lang.NoClassDefFoundError, com/mysql/cj/exceptions/CJCommunicationsException

### ISSUE THREAD

**Issue by laurentperez** [quarkusio/quarkus#16488]
## Describe the bug
We are trialing quarkus1.12/13, so far it's great except we are using an old mysql5, so our jdbc driver has to be mysql:mysql-connector-java:5.1.49
I know our legacy db is old, and quarkus bom / jdbc-driver-mysql bundles the 8.0.23 jdbc driver. 
Quarkus runDev fails to compile with 5.1.49 driver at MySQLJDBCReflections with :
```
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.jdbc.mysql.deployment.MySQLJDBCReflections#registerExceptionsForReflection threw an exception: java.lang.NoClassDefFoundError: com/mysql/cj/exceptions/CJCommunicationsException
        at io.quarkus.jdbc.mysql.deployment.MySQLJDBCReflections.registerExceptionsForReflection(MySQLJDBCReflections.java:92)

```

Located at https://github.com/quarkusio/quarkus/blob/2ceef3da23ebb262c81e2616a777ef33ecde356d/extensions/jdbc/jdbc-mysql/deployment/src/main/java/io/quarkus/jdbc/mysql/deployment/MySQLJDBCReflections.java#L92

I understand there may be more NoClassDefFoundError following in the com.mysql.cj package.
I did not test runtime, we stopped at deployment.

### Expected behavior
Mysql5 driver is supported
I understand Quarkus is modern, yet supporting legacy mysql dbs would be great

### Actual behavior
see above

## To Reproduce

1.  replace mysql connector jar 8.0.23 with 5.1.49
2.  gradle runDev

## Environment (please complete the following information):
java11 quarkus1.12

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
gradle

**Comment by laurentperez** [comment]
cf https://github.com/quarkusio/quarkus/issues/2323

**Comment by gsmet** [comment]
Have you tested to use the new driver with your old database? Often, drivers support old versions pretty well.

Apart from that, that's not a usage we will support so if you want to do that, don't use the MySQL extension. Set the db-kind to other and define the driver yourself by adding the dependency directly. Just adapt the example we have in the doc for Oracle: https://quarkus.io/guides/datasource#other-databases .

It won't work in native though.

**Comment by laurentperez** [comment]
Yep, we have a mysqld5.1 rdbms, I know, it's old. Unfortunately the 8.0.23 from quarkus bom/jdbcmysql does not support it, it requires mysqld5.5.

Also, the quarkus flyway extension requires mysqld >= 5.7. This is because it's the community edition of flyway, older rdbms are supported only with the paid version.

Thank you for the Oracle tip, we'll look into it.

**Comment by laurentperez** [comment]
Thank you Guillaume, "other" worked. We just had to exclude the 8.0.23 driver too from the BOM with

```
    implementation enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}") {
        exclude group: 'mysql', module: 'mysql-connector-java'
    }

```
Any possible tradeoffs when not using the extension, impacts on Agroal/JTA XA, maybe (?)

Apart from the native obviously.

**Comment by gsmet** [comment]
That will be missing https://github.com/quarkusio/quarkus/blob/1.13/extensions/jdbc/jdbc-mysql/runtime/src/main/java/io/quarkus/jdbc/mysql/runtime/MySQLAgroalConnectionConfigurer.java#L19 as it's configured automatically under the hood.

I don't think we provide a way to configure it manually though. But this feature is new so it should work OK.

**Comment by laurentperez** [comment]
I close this ticket, because we managed to downgrade the driver to mysql5.1, and removed the flyway extension because it requires mysqld 5.7 and our db is older.

Also the jdbc 8.0 driver requires jdk8, so afaik there is no real point in retrofiting the jdbc extension to support the 5.x driver, since Quarkus itself requires a jdk8, maybe even 11 for quarkus2

Still for legacy ports of Spring Boot apps, based on mysql5.x, this ticket may contain information for future readers.
