### ISSUE TITLE
JaCoCo seems to no longer works in Quarkus 3.22

### ISSUE THREAD

**Issue by Fabccc** [quarkusio/quarkus#47722]
### Describe the bug

Hi,

I'm having an issue, since I upgraded to Quarkus 3.22.1 from Quarkus 3.19.4, JaCoCo reports show 0 percent code coverage, and didn't detetect generated class from mapstruct.

Ref #43419 

### Expected behavior

I should have at least some code / branch coverage in green.

### Actual behavior

All reports show 0% in code and branch coverage, and it can't detect generated sources like mapstruct.

### How to Reproduce?

I will work on a reproducer in the week

### Output of `uname -a` or `ver`

Linux fabcc-arch 6.14.4-arch1-2 #\1 SMP PREEMPT_DYNAMIC Tue, 29 Apr 2025 09:23:13 +0000 x86_64 GNU/Linux

### Output of `java -version`

openjdk 24.0.1 2025-04-15 OpenJDK Runtime Environment (build 24.0.1) OpenJDK 64-Bit Server VM (build 24.0.1, mixed mode, sharing)

### Quarkus version or git rev

3.22.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae) Maven home: /home/fabcc/.m2/wrapper/dists/apache-maven-3.9.6/a53741d1 Java version: 24.0.1, vendor: Arch Linux, runtime: /usr/lib/jvm/java-24-openjdk Default locale: fr_FR, platform encoding: UTF-8 OS name: "linux", version: "6.14.4-arch1-2", arch: "amd64", family: "unix"

**Comment by geoand** [comment]
Thanks for reporting.

Can you please attach a sample project that shows the test coverage working in 3.19 and not in 3.22?

**Comment by Fabccc** [comment]
I got it working by changing my pom.xml.
I had a the `jacoco-maven-plugin` plugin in my script, I removed it.
My configuration for surefire plugin was the following:
```xml
<plugin>
	<artifactId>maven-surefire-plugin</artifactId>
	<version>${surefire-plugin.version}</version>
	<configuration>
		<argLine>@{argLine} --enable-preview</argLine>
		<systemPropertyVariables>
			<java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
			<maven.home>${maven.home}</maven.home>
		</systemPropertyVariables>
	</configuration>
</plugin>
```

The @{argLine} was intended for property replacement in the JaCoCo plugin agent, but it caused a compilation error:
Error: could not open '{argLine}'.

After removing my custom JaCoCo Maven plugin configuration and the @{argLine} placeholder, the build succeeded.

Closing the issue—sorry for the false positive.

**Comment by geoand** [comment]
Thanks for the update!

**Comment by pmsmm** [comment]
Hey @geoand thanks for getting back to me so quicly, here is the stack trace I get after updating from 3.21.4 to 3.23.0 

```
java.lang.RuntimeException: java.lang.RuntimeException: Failed to locate com/siemens/sfs/expand/funding/appservices/jaxrs/error/providers/ExpandApplicationExceptionMapperTest.class among the application dependencies
	at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:667)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestClassConstructor(QuarkusTestExtension.java:762)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.lang.RuntimeException: Failed to locate com/siemens/sfs/expand/funding/appservices/jaxrs/error/providers/ExpandApplicationExceptionMapperTest.class among the application dependencies
	at io.quarkus.test.common.PathTestHelper.getTestClassesLocation(PathTestHelper.java:188)
	at io.quarkus.test.common.PathTestHelper.getTestClassesLocation(PathTestHelper.java:229)
	at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:204)
	at io.quarkus.test.junit.QuarkusTestExtension.ensureStarted(QuarkusTestExtension.java:641)
	at io.quarkus.test.junit.QuarkusTestExtension.beforeAll(QuarkusTestExtension.java:686)
	... 1 more
```

**Comment by geoand** [comment]
Any chance you can attach a sample I can use to see the problem in action?

**Comment by geoand** [comment]
Without a reproducer (it doesn't have to be the actual project you are working on, just a small project that exhibits the same issue you describe), there is not much we can do
