### ISSUE TITLE
Gradle QuarkusTest fails with Compilation Failed when using lombok on reload

### ISSUE THREAD

**Issue by Malandril** [quarkusio/quarkus#50936]
### Describe the bug

When using the lombok gradle plugin with the `quarkusTest` task , the live reload fails with

```
Compilation Failed:
/src/main/java/org/acme/GreetingResource.java:8: error: package lombok.extern.slf4j does not exist
import lombok.extern.slf4j.Slf4j;
```

This does not happen when running `quarkusDev` , and in continuous testing with `quarkusDev`

### How to Reproduce?

Reproducer : [https://github.com/Malandril/quarkus-bug-lombok-test](https://github.com/Malandril/quarkus-bug-lombok-test)

run `./gradlew quarkusTest`

Then change anything in the `GreetingResource` class, it wail fail with a compilation error

### Output of `java -version`

21

### Quarkus version or git rev

3.29.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

9.1.0

### Additional information

It is caused by #50253 , more precisely the commit 1ed554b6abc831138610d808703d9bf8f0b1f8b0 , reverting it fixes the issue.

**Comment by Malandril** [comment]
@aloubyansky Maybe you have an idea on why https://github.com/quarkusio/quarkus/commit/1ed554b6abc831138610d808703d9bf8f0b1f8b0 might cause this issue ?
