### ISSUE TITLE
Rest route does not work with version 2.10.x

### ISSUE THREAD

**Issue by DiegoBetancourtC** [quarkusio/quarkus#26687]
### Describe the bug

If you try to create a simple rest api using a route, it won't work using 2.10.x but if you change it to version 2.7.1, it works without any problem.

Based on the documentation [Rest](https://camel.apache.org/camel-quarkus/2.10.x/reference/extensions/rest.html) 

### Expected behavior

It should compile without any problems

### Actual behavior

I got an error at the moment of compiling:

`./mvnw clean compile quarkus:dev`

```
cannot find symbol
[ERROR]   symbol:   method route()
[ERROR]   location: class org.apache.camel.model.rest.RestDefinition
```

### How to Reproduce?

Create a simple class:

```
package org.acme;

import javax.enterprise.context.ApplicationScoped;
import org.apache.camel.builder.RouteBuilder;

@ApplicationScoped
public class GreetingResource extends RouteBuilder
{
    @Override
    public void configure() throws Exception {
        from("direct:some-service")
            .log("Information Received: ")
            .log("--> body: [${body}]");

        rest("/v1")
            .get("/path")
            .route()
                .to("direct:some-service")
            .endRest();
    }
}
```
Compile it:

`./mvnw clean compile quarkus:dev`

You will get the cannot find symbol error. If you go to your pom.xml file and change it to version 2.7.1.Final:

```
...
  <properties>
    <compiler-plugin.version>3.8.1</compiler-plugin.version>
    <maven.compiler.release>11</maven.compiler.release>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <quarkus.platform.artifact-id>quarkus-bom</quarkus.platform.artifact-id>
    <quarkus.platform.group-id>io.quarkus.platform</quarkus.platform.group-id>
    <quarkus.platform.version>2.7.1.Final</quarkus.platform.version>
    <skipITs>true</skipITs>
    <surefire-plugin.version>3.0.0-M7</surefire-plugin.version>
  </properties>
...
```
Then it compiles without any problem.

### Output of `uname -a` or `ver`

Darwin Kernel Version 21.5.0

### Output of `java -version`

java version "1.8.0_191"

### Quarkus version or git rev

2.10.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)

**Comment by gsmet** [comment]
Could you provide a reproducer so that we can have a look? Thanks.

**Comment by DiegoBetancourtC** [comment]
> Could you provide a reproducer so that we can have a look? Thanks.

Sure, [code-with-quarkus-12.zip](https://github.com/quarkusio/quarkus/files/9095270/code-with-quarkus-12.zip)

1. Decompress
2. Go to the folder and execute the command: `./mvnw clean compile quarkus:dev`
3. You should get the following error:

```
[INFO] Scanning for projects...
[INFO]
[INFO] ---------------------< org.acme:code-with-quarkus >---------------------
[INFO] Building code-with-quarkus 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ code-with-quarkus ---
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ code-with-quarkus ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO]
[INFO] --- quarkus-maven-plugin:2.10.1.Final:generate-code (default) @ code-with-quarkus ---
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ code-with-quarkus ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /Users/some/Downloads/code-with-quarkus-12/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /Users/some/Downloads/code-with-quarkus-12/src/main/java/org/acme/GreetingResource.java:[17,13] cannot find symbol
  symbol:   method route()
  location: class org.apache.camel.model.rest.RestDefinition
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.492 s
[INFO] Finished at: 2022-07-12T11:55:28-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project code-with-quarkus: Compilation failure
[ERROR] /Users/some/Downloads/code-with-quarkus-12/src/main/java/org/acme/GreetingResource.java:[17,13] cannot find symbol
[ERROR]   symbol:   method route()
[ERROR]   location: class org.apache.camel.model.rest.RestDefinition
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

Thanks for the quick reply.

**Comment by DiegoBetancourtC** [comment]
Thank you, didn't see that guide.
