### ISSUE TITLE
NoSuchMethodError: void org.hibernate.boot.internal.MetadataImpl.<init> when Upgrading Hibernate to 6.6.0.CR1

### ISSUE THREAD

**Issue by hantsy** [quarkusio/quarkus#41406]
### Describe the bug

```bash 
Caused by: java.lang.NoSuchMethodError: 'void org.hibernate.boot.internal.MetadataImpl.<init>(java.util.UUID, org.hibernate.boot.spi.MetadataBuildingOptions, java.util.Map, java.util.List, java.util.Map, java.util.Map, java.util.Map, java.util.Map, java.util.Map, java.util.Map, java.util.Map, java.util.Map, java.util.Map, java.util.Map, java.util.Map, java.util.Map, java.util.Map, java.util.Map, org.hibernate.boot.model.relational.Database, org.hibernate.boot.spi.BootstrapContext)'
	at io.quarkus.hibernate.orm.runtime.boot.FastBootMetadataBuilder.trimBootstrapMetadata(FastBootMetadataBuilder.java:469)
	at io.quarkus.hibernate.orm.runtime.boot.FastBootMetadataBuilder.build(FastBootMetadataBuilder.java:432)
	at io.quarkus.hibernate.orm.runtime.PersistenceUnitsHolder.createMetadata(PersistenceUnitsHolder.java:101)
	at io.quarkus.hibernate.orm.runtime.PersistenceUnitsHolder.constructMetadataAdvance(PersistenceUnitsHolder.java:73)
	at io.quarkus.hibernate.orm.runtime.PersistenceUnitsHolder.initializeJpa(PersistenceUnitsHolder.java:40)
	at io.quarkus.hibernate.orm.runtime.HibernateOrmRecorder$1.created(HibernateOrmRecorder.java:78)
	at io.quarkus.arc.runtime.ArcRecorder.initBeanContainer(ArcRecorder.java:80)
	at io.quarkus.deployment.steps.ArcProcessor$notifyBeanContainerListeners1304312071.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.ArcProcessor$notifyBeanContainerListeners1304312071.deploy(Unknown Source)
	... 9 more

```

### Expected behavior

Should work as 6.6.0.Alpha1

### Actual behavior

Check the build stack:https://github.com/hantsy/quarkus-sandbox/actions/runs/9654716441/job/26629425710?pr=2308

### How to Reproduce?

Check the jakarta data example in https://github.com/hantsy/quarkus-sandbox

### Output of `uname -a` or `ver`

Windows 10

### Output of `java -version`

21

### Quarkus version or git rev

3.12.0.CR1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

3.9.7

**Comment by yrodiere** [comment]
Thanks for reporting.

Quarkus is deisgned to work with a specific version of Hibernate ORM, and tightly integrated with that version.
Overriding the version of Hibernate ORM in applications is therefore not supported.

FWIW, work on upgrading Quarkus to Hibernate ORM 6.6 is in progress: https://github.com/quarkusio/quarkus/pull/41359
