### ISSUE TITLE
NoClassDefFoundError after quarkus update in multi module project

### ISSUE THREAD

**Issue by mseelzeiss** [quarkusio/quarkus#48876]
### Describe the bug

After upgrading to the version 3.24.3 from 3.21.0 in a multi module project we face the following issue in our AzureDevops pipeline run (which is a linux agent)

We where not able to reproduce this in IntelliJ locally on a windows machine.

-----

java.lang.NoClassDefFoundError: Could not initialize class io.quarkus.test.common.TestScopeManager
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160)
	at java.base/java.lang.reflect.Method.acquireMethodAccessor(Method.java:726)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at io.quarkus.test.junit.QuarkusTestExtension.beforeEach(QuarkusTestExtension.java:411)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.tryRemoveAndExec(ForkJoinPool.java:1351)
	at java.base/java.util.concurrent.ForkJoinTask.awaitDone(ForkJoinTask.java:422)
	at java.base/java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:651)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
	Suppressed: java.lang.NoClassDefFoundError: Could not initialize class io.quarkus.test.common.TestScopeManager
		at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
		at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160)
		at java.base/java.lang.reflect.Method.acquireMethodAccessor(Method.java:726)
		at java.base/java.lang.reflect.Method.invoke(Method.java:577)
		at io.quarkus.test.junit.QuarkusTestExtension.afterEach(QuarkusTestExtension.java:531)
		... 9 more
	Caused by: java.lang.ExceptionInInitializerError: Exception java.util.ServiceConfigurationError: io.quarkus.runtime.test.TestScopeSetup: io.quarkus.arc.runtime.ArcTestRequestScopeProvider not a subtype [in thread "ForkJoinPool-1-worker-2"]
		at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:593)
		at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1244)

-----

Environment Information:

Linux 
msopenjdk-21

### Expected behavior

Test runs with issues as in quarkus 3.21.0

### Actual behavior

Tests are failing with error

### Output of `java -version`

21

### Quarkus version or git rev

3.24.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvnw 3.9.3

### Additional information

We also updated the quarkus version 3.24.3 in another project without multi module. There everything works fine.

**Comment by geoand** [comment]
cc @holly-cummins @mkouba

**Comment by geoand** [comment]
Is this still an issue with the latest versions of Quarkus?

**Comment by geoand** [comment]
Closing for lack of feedback
