### PR TITLE
Add compile-only dependencies to the dev mode compiler classpath

### LINKED ISSUE #50936: Gradle QuarkusTest fails with Compilation Failed when using lombok on reload
### Describe the bug

When using the lombok gradle plugin with the `quarkusTest` task , the live reload fails with

```
Compilation Failed:
/src/main/java/org/acme/GreetingResource.java:8: error: package lombok.extern.slf4j does not exist
import lombok.extern.slf4j.Slf4j;
```

This does not happen when running `quarkusDev` , and in continuous testing with `quarkusDev`

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

Reproducer : [https://github.com/Malandril/quarkus-bug-lombok-test](https://github.com/Malandril/quarkus-bug-lombok-test)

run `./gradlew quarkusTest`

Then change anything in the `GreetingResource` class, it wail fail with a compilation error

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

21

### Quarkus version or git rev

3.29.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

9.1.0

### Additional information

It is caused by #50253 , more precisely the commit 1ed554b6abc831138610d808703d9bf8f0b1f8b0 , reverting it fixes the issue.

### PR DESCRIPTION
**Pull request by aloubyansky**
- Fixes: https://github.com/quarkusio/quarkus/issues/50936

### CODE REVIEW

**Comment by aloubyansky** [comment]
@gsmet @geoand would one of you review this one? Thanks.

**Review by geoand — APPROVED** [review]
LGTM!

**Comment by geoand** [comment]
Should this be backported?

**Comment by aloubyansky** [comment]
It could be, added a label. Thanks!
