### PR TITLE
Reorder gradle code generation task

### LINKED ISSUE #11641: Quarkus 1.7.x: Gradle Kotlin project compilation error
**Describe the bug**
After upgrading my Quarkus (gradle, Kotlin) project from 1.6.1.Final to 1.7.0.Final, I get a compilation error 

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':common:quarkusPrepareTests'.
> Cannot change dependencies of dependency configuration ':common:kotlinCompilerPluginClasspath' after it has been resolved.

```

**To Reproduce**
1. Download reproducer project and unzip it [2020-08-25_kotlin-compiling-issues.zip](https://github.com/quarkusio/quarkus/files/5129529/2020-08-25_kotlin-compiling-issues.zip)
2. Run `./gradlew check` in the project directory
3. The build fails with the error shown above
4. Change the Quarkus version in gradle.properties to 1.6.1.Final and it works

**Environment (please complete the following information):**
 - Quarkus 1.7.0
- Windows 10
- JDK 11

### PR DESCRIPTION
**Pull request by glefloch**
This branch makes sure `quarkusGenerateCode` and `quarkusGenerateCodeTests` are ran before `compileJava` and `compileKotlin` tasks. 

Close #11641 #11670

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]
LGTM

**Review by aloubyansky — APPROVED** [review]

File: devtools/gradle/src/main/java/io/quarkus/gradle/QuarkusPlugin.java [hunk 1]
```diff
@@ -137,13 +136,12 @@ public void execute(Task test) {
...
-                    compileJavaTask.mustRunAfter(quarkusGenerateCode);
+                    compileJavaTask.dependsOn(quarkusGenerateCode);
                     quarkusGenerateCode.setSourceRegistrar(compileJavaTask::source);
 
-                    try {
-                        // TODO: support kotlin
-                        tasks.getByName("compileTestKotlin");
-                    } catch (UnknownTaskException noKotlin) {
+                    Task compileKotlinTask = tasks.findByName("compileKotlin");
+                    // TODO: proper support of kotlin
```
Comment (michalszynkiewicz) [inline devtools/gradle/src/main/java/io/quarkus/gradle/QuarkusPlugin.java:143]: can the todo be removed now? (not necessarily in this PR :) )

**Review by michalszynkiewicz — APPROVED** [review]
