### ISSUE TITLE
Native mode, app with quarkus-smallrye-fault-tolerance, getting java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#3737]
I see `java.lang.NoClassDefFoundError` in native mode with app using `quarkus-smallrye-fault-tolerance`, native build passes if you comment out quarkus-smallrye-fault-tolerance dependency.

The main cause is `Caused by: java.lang.ClassNotFoundException: io.smallrye.context.propagators.rxjava2.RxJava2ContextPropagator` (part of smallrye-context-propagation dependency)

This issue is not present when using Quarkus 0.21.1 which uses GraalVM 19.1.1 and smallrye-context-propagation 1.0.7.
Master uses GraalVM 19.2.0 and smallrye-context-propagation 1.0.11.
I tried Quarkus 0.21.1 + explicit definition smallrye-context-propagation version to 1.0.11 and it passed. Seems GraalVM 19.2.0 is more aggressive in elimination.

Steps to reproduce:
```
git clone https://github.com/quarkus-qe/beefy-scenarios.git
cd beefy-scenarios
mvn clean install -Dnative -pl 101-javaee-like-getting-started
```

Details:
```
[INFO] [io.quarkus.creator.phase.nativeimage.NativeImagePhase] /Users/rsvoboda/.sdkman/candidates/java/19.2.0-grl/bin/native-image -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Drx.unsafe-disable=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dvertx.disableDnsResolver=true -J-Dio.netty.noUnsafe=true --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy$BySpaceAndTime -jar 101-javaee-like-getting-started-1.0.0-SNAPSHOT-runner.jar -J-Djava.util.concurrent.ForkJoinPool.common.parallelism=1 -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:+PrintAnalysisCallTree -H:-AddAllCharsets -H:EnableURLProtocols=http,https --enable-all-security-services -H:-SpawnIsolates -H:+JNI --no-server -H:-UseServiceLoaderFeature -H:+StackTrace
[101-javaee-like-getting-started-1.0.0-SNAPSHOT-runner:12474]    classlist:  10,566.74 ms
[101-javaee-like-getting-started-1.0.0-SNAPSHOT-runner:12474]        (cap):   2,022.97 ms
[101-javaee-like-getting-started-1.0.0-SNAPSHOT-runner:12474]        setup:   3,725.23 ms
12:46:50,180 INFO  [org.jbo.threads] JBoss Threads version 3.0.0.Beta5
12:46:51,002 INFO  [com.arj.ats.arjuna] ARJUNA012170: TransactionStatusManager started on port 54935 and host 127.0.0.1 with service com.arjuna.ats.arjuna.recovery.ActionStatusService
[101-javaee-like-getting-started-1.0.0-SNAPSHOT-runner:12474]     analysis:  15,258.36 ms
Printing call tree to /Users/rsvoboda/git/beefy-scenarios/101-javaee-like-getting-started/target/reports/call_tree_101-javaee-like-getting-started-1.0.0-SNAPSHOT-runner_20190827_124706.txt
Printing list of used classes to /Users/rsvoboda/git/beefy-scenarios/101-javaee-like-getting-started/target/reports/used_classes_101-javaee-like-getting-started-1.0.0-SNAPSHOT-runner_20190827_124707.txt
Printing list of used packages to /Users/rsvoboda/git/beefy-scenarios/101-javaee-like-getting-started/target/reports/used_packages_101-javaee-like-getting-started-1.0.0-SNAPSHOT-runner_20190827_124707.txt
Error: Class initialization of io.quarkus.runner.ApplicationImpl1 failed. Use the option --initialize-at-run-time=io.quarkus.runner.ApplicationImpl1 to explicitly request delayed initialization of this class.
Detailed message:

com.oracle.svm.core.util.UserError$UserException: Class initialization of io.quarkus.runner.ApplicationImpl1 failed. Use the option --initialize-at-run-time=io.quarkus.runner.ApplicationImpl1 to explicitly request delayed initialization of this class.
Detailed message:

	at com.oracle.svm.core.util.UserError.abort(UserError.java:75)
	at com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:223)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:737)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:526)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:444)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Class initialization of io.quarkus.runner.ApplicationImpl1 failed. Use the option --initialize-at-run-time=io.quarkus.runner.ApplicationImpl1 to explicitly request delayed initialization of this class.
Detailed message:

	at com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:130)
	at com.oracle.graal.pointsto.BigBang.finish(BigBang.java:565)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:688)
	... 7 more
Caused by: java.lang.ExceptionInInitializerError
	at sun.misc.Unsafe.ensureClassInitialized(Native Method)
	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.ensureClassInitialized(ConfigurableClassInitialization.java:153)
	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.computeInitKindAndMaybeInitializeClass(ConfigurableClassInitialization.java:557)
	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.computeInitKindAndMaybeInitializeClass(ConfigurableClassInitialization.java:116)
	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.maybeInitializeHosted(ConfigurableClassInitialization.java:144)
	at com.oracle.svm.hosted.SVMHost.registerType(SVMHost.java:190)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.createType(AnalysisUniverse.java:262)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:203)
	at com.oracle.graal.pointsto.infrastructure.WrappedConstantPool.lookupType(WrappedConstantPool.java:155)
	at org.graalvm.compiler.java.BytecodeParser.lookupType(BytecodeParser.java:4080)
	at org.graalvm.compiler.java.BytecodeParser.genNewInstance(BytecodeParser.java:4330)
	at org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5128)
	at org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3267)
	at org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3074)
	at org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:976)
	at org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:870)
	at org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:84)
	at org.graalvm.compiler.phases.Phase.run(Phase.java:49)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
	at org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
	at org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:221)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:340)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:310)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:300)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:107)
	at com.oracle.graal.pointsto.flow.StaticInvokeTypeFlow.update(InvokeTypeFlow.java:346)
	at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:510)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:171)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	... 4 more
Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl1.<clinit>(ApplicationImpl1.zig:445)
	... 34 more
Caused by: java.lang.NoClassDefFoundError: io/smallrye/context/propagators/rxjava2/RxJava2ContextPropagator
	at io.quarkus.deployment.steps.SmallRyeContextPropagationProcessor$buildStatic11.deploy_0(SmallRyeContextPropagationProcessor$buildStatic11.zig:200)
	at io.quarkus.deployment.steps.SmallRyeContextPropagationProcessor$buildStatic11.deploy(SmallRyeContextPropagationProcessor$buildStatic11.zig:36)
	at io.quarkus.runner.ApplicationImpl1.<clinit>(ApplicationImpl1.zig:327)
	... 34 more
Caused by: java.lang.ClassNotFoundException: io.smallrye.context.propagators.rxjava2.RxJava2ContextPropagator
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 37 more
```

**Comment by rsvoboda** [comment]
The same issue is seen in quickstarts - microprofile-fault-tolerance
@gsmet fyi

**Comment by kenfinnigan** [comment]
@rsvoboda can you verify with 0.27?

I'd be surprised if this is still an issue

**Comment by rsvoboda** [comment]
ok, will look into it tmr

**Comment by rsvoboda** [comment]
This can be closed, issue has been fixed.

I had to adjust my pom.xml to work with 0.27.0
```diff
diff --git a/pom.xml b/pom.xml
index 64c4902..dd1b5e3 100644
--- a/pom.xml
+++ b/pom.xml
@@ -84,22 +84,6 @@
       </activation>
       <build>
         <plugins>
-          <plugin>
-            <groupId>io.quarkus</groupId>
-            <artifactId>quarkus-maven-plugin</artifactId>
-            <version>${quarkus.version}</version>
-            <executions>
-              <execution>
-                <goals>
-                  <goal>native-image</goal>
-                </goals>
-                <configuration>
-                  <enableHttpUrlHandler>true</enableHttpUrlHandler>
-                  <additionalBuildArgs></additionalBuildArgs>
-                </configuration>
-              </execution>
-            </executions>
-          </plugin>
           <plugin>
             <artifactId>maven-failsafe-plugin</artifactId>
             <version>${surefire-plugin.version}</version>
@@ -119,6 +103,9 @@
           </plugin>
         </plugins>
       </build>
+      <properties>
+        <quarkus.package.type>native</quarkus.package.type>
+      </properties>
     </profile>
   </profiles>
 </project>
```
