### PR TITLE
Fix Gradle compilation against code generated by custom providers

### LINKED ISSUE #50123: 3.26.2 with gradle doesn't see sources generated by quarkus-openapi-generator
### Describe the bug

https://github.com/Shohou/quarkus_openapi_3_26_2
This repository contains a quarkus project generated by code.quarkus.io with two libraries: `OpenApi Generator - REST Client Generator` and `REST Client Jackson`. Build tool `gradle`. The only change is in GreetingResource, it now returns model generated by openapi generator.

With version 3.26.2 (and also 3.26.3) in gradle.properties it fails to compile with error "GreetingResource.java:7: error: package org.openapi.quarkus.openapi_yml.model does not exist"
Changing version to 3.26.1 fixes the issue and project compiles successfully.

### Expected behavior

Project should work with version 3.26.2 and 3.26.3

### Actual behavior

compilation erros

### How to Reproduce?

See https://github.com/Shohou/quarkus_openapi_3_26_2

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradle

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by MdTanwer**
Since 3.26.2 the Gradle plugin only registered the hardcoded `grpc`/`avro` codegen provider directories as compile sources. As a result, application code could no longer compile against sources produced by other code generation providers — most notably the Quarkiverse OpenAPI generator (`open-api`) — even though the files were generated on disk. IDEs also stopped resolving those generated types.

This derives the compile source roots from the `quarkusGenerateCode` task outputs and registers each provider output directory individually, so every provider id is covered instead of a fixed list. The generated outputs are intentionally not attached to the main source set, since doing so reintroduces the KSP circular dependency

- Fixes: #50123

### CODE REVIEW

**Comment by geoand** [comment]
Also cc @snazy

**Review by aloubyansky — DISMISSED** [review]
Thanks @MdTanwer

**Comment by geoand** [comment]
The CI failures seem related

**Comment by MdTanwer** [comment]
> The CI failures seem related

@aloubyansky, @geoand I fixed the CI failure. Could you please take a look? :)

**Review by aloubyansky — APPROVED** [review]
