### ISSUE TITLE
2.7.2 issues with XMLInputFactory after migrating from 2.6.3

### ISSUE THREAD

**Issue by asathe** [quarkusio/quarkus#23994]
We're seeing an error when using jackson XmlFactory:
Caused by: java.lang.NoSuchMethodError: 'javax.xml.stream.XMLInputFactory javax.xml.stream.XMLInputFactory.newFactory(java.lang.String, java.lang.ClassLoader)'

Gradle file includes:
'com.fasterxml.jackson.dataformat:jackson-dataformat-xml'
'com.fasterxml.woodstox:woodstox-core:6.2.5'

`XmlMapper.builder()
.defaultUseWrapper(false)
.build()
.registerModule(KotlinModule())`

**Comment by gsmet** [comment]
Could you please provide a reproducer i.e. a small project reproducing the issue?

**Comment by gsmet** [comment]
My guess would be that the versions you are using are somehow incompatible.

**Comment by asathe** [comment]
I'll look to get a little reproducer setup shortly, thanks

**Comment by grossws** [comment]
I had similar case with present `org.codehaus.woodstox:woodstox-core-asl` in runtime classpath that brought old version of the `javax.xml.stream:stax-api` that also has `javax.xml.stream.XMLInputFactory` without `newFactory(String,ClassLoader)` static method.

**Comment by tarekahf** [comment]
> I had similar case with present `org.codehaus.woodstox:woodstox-core-asl` in runtime classpath that brought old version of the `javax.xml.stream:stax-api` that also has `javax.xml.stream.XMLInputFactory` without `newFactory(String,ClassLoader)` static method.
@grossws 
I changed the dependency of `jackson-dataformat-xml` from 2.14.2 down to 2.12.7 and the problem was resolved. Thank you for inspiring me to find the solution.

**Comment by gsmet** [comment]
Closing as the problem only arises when mixing incompatible versions of components.

**Comment by tarekahf** [comment]
> Closing as the problem only arises when mixing incompatible versions of components.

I thought that Maven would ensure getting the dependencies correctly. I still cannot understand how lowering the version for `jackson-dataformat-xml` would solve the problem. If anyone can explain how this solved the problem, I appreciate your feedback.

**Comment by gsmet** [comment]
My guess is that the old version of Jackson is compatible with the old version of the XML stack you have in your classpath. You probably need to use `mvn dependency:tree` and try to understand what is coming with the old XML APIs.

**Comment by tarekahf** [comment]
> My guess is that the old version of Jackson is compatible with the old version of the XML stack you have in your classpath. You probably need to use `mvn dependency:tree` and try to understand what is coming with the old XML APIs.

One more thing is that it was working during Unit Testung (junit classes) but I used to get the error only when I deploy my code over to a running instance. The final component uses multi threading extensively and loads classes or jars during the runtime.

I need to find out how to troubleshoot this issue during run time not in the design or compile/test time under eclipse.

Appreciate it if you can give me some pointers...

**Comment by dinuta** [comment]
Hi guys,
The issue in most cases is in the classpath. Wanted to use 2.14.2 but failed because of other deps which had priority, and there was not the method newFactory(), only newInstance()

Steps to debug:
1. mvn dependency:tree 
2. in intellij (or other IDE) search for class XMLInputFactory in the entire maven scope

Now based on IDE you found the dependencies you should exclude (or align the version, depending on the constraints).
For me I excluded:
```
 <exclusion>
     <groupId>xml-apis</groupId>
     <artifactId>xml-apis</artifactId>
   </exclusion>

 <exclusion>
    <groupId>org.apache.geronimo.specs</groupId>
                  <artifactId>geronimo-stax-api_1.0_spec</artifactId>
</exclusion>
```
