### ISSUE TITLE
java.lang.NoSuchMethodError: org.jboss.resteasy.reactive.server.core.parameters.converters.LocalDateParamConverter

### ISSUE THREAD

**Issue by koalalam** [quarkusio/quarkus#23697]
### Describe the bug

Application failed to start when upgrading Quarkus from 2.5.1 to 2.7.1.

Default constructor is removed since 2.6:
* https://github.com/quarkusio/quarkus/blob/2.5/independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/core/parameters/converters/LocalDateParamConverter.java
* https://github.com/quarkusio/quarkus/blob/2.6/independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/core/parameters/converters/LocalDateParamConverter.java

```java
import java.time.LocalDate;
import javax.ws.rs.QueryParam;

public class SummaryRequest {

  @QueryParam("tradeDate")
  private LocalDate tradeDate;

  public LocalDate getTradeDate() {
    return tradeDate;
  }

  public void setTradeDate(LocalDate tradeDate) {
    this.tradeDate = tradeDate;
  }
}
```

```java
import java.util.concurrent.CompletionStage;
import javax.validation.Valid;
import javax.ws.rs.BeanParam;
import javax.ws.rs.GET;
import javax.ws.rs.Path;

public interface TradeResource {

  @Path("/summary")
  @GET
  CompletionStage<SummaryResponse> getSummary(@Valid @BeanParam SummaryRequest request);
}
```

### Expected behavior

Application starts successfully

### Actual behavior

Application failed to start with below stacktrace:

```
Caused by: java.lang.NoSuchMethodError: org.jboss.resteasy.reactive.server.core.parameters.converters.LocalDateParamConverter: method <init>()V not found
	at x.y.z.SummaryRequest.__quarkus_init_converter__tradeDate(SummaryRequest.java)
	at io.quarkus.rest.runtime.__QuarkusInit.init(Unknown Source)
	at io.quarkus.resteasy.reactive.server.runtime.ResteasyReactiveRecorder.createDeployment(ResteasyReactiveRecorder.java:122)
	at io.quarkus.deployment.steps.ResteasyReactiveProcessor$setupDeployment1557341086.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.ResteasyReactiveProcessor$setupDeployment1557341086.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl.<clinit>(Unknown Source)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:103)
	... 1 more
```

### Quarkus version or git rev

2.7.1
