### ISSUE TITLE
3.26.2 with gradle doesn't see sources generated by quarkus-openapi-generator

### ISSUE THREAD

**Issue by Shohou** [quarkusio/quarkus#50123]
### Describe the bug

https://github.com/Shohou/quarkus_openapi_3_26_2
This repository contains a quarkus project generated by code.quarkus.io with two libraries: `OpenApi Generator - REST Client Generator` and `REST Client Jackson`. Build tool `gradle`. The only change is in GreetingResource, it now returns model generated by openapi generator.

With version 3.26.2 (and also 3.26.3) in gradle.properties it fails to compile with error "GreetingResource.java:7: error: package org.openapi.quarkus.openapi_yml.model does not exist"
Changing version to 3.26.1 fixes the issue and project compiles successfully.

### Expected behavior

Project should work with version 3.26.2 and 3.26.3

### Actual behavior

compilation erros

### How to Reproduce?

See https://github.com/Shohou/quarkus_openapi_3_26_2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradle

**Comment by phillip-kruger** [comment]
It's probably better log log this issue in https://github.com/quarkiverse/quarkus-openapi-generator

**Comment by xco-sk** [comment]
We observe a similar problem with proto-generated classes, so this is most likely not openapi specific. Seems like Gradle plugin version 3.26.2+ does not register `/build/classes/java/quarkus-generated-sources/` path for main and test source sets.

I've checked with this Gradle task:
```
tasks.register("sourceSets", DefaultTask::class) {
    group = "help"

    sourceSets.forEach {
        println("Source set: $it")
        val s = HashSet<String>()
        it.allSource.forEach { s.add(it.parent.replaceFirst(project.projectDir.path, "")) }
        val l = s.toList().sorted()

        l.forEach { println("Path: $it")}
    }
}
```
And 3.26.2 and 3.26.3 show only `/src/main/` and `/src/test/` prefixed paths, while 3.26.1 also contains `/build/classes/java/quarkus-generated-sources/`-prefixed paths.

btw. Even IntelliJ doesn't see proto-generated classes and shows them in red in 3.26.2+.

**Comment by aloubyansky** [comment]
> Seems like Gradle plugin version 3.26.2+ does not register /build/classes/java/quarkus-generated-sources/ path for main and test source sets.

That is true. The question is should the generated sources be added to the main source sets, since they are different source sets.

**Comment by aloubyansky** [comment]
I mean, projects should be buildable at the end. The question is how these source sets should be handled.

**Comment by shokhodja** [comment]
The issue still persists in version 3.28.1. Any updates on this?
