### PR TITLE
Fall back to ThreadLocal if Netty is not present

### LINKED ISSUE #19247: Agroal has a reference to a Netty class while not depending on it
### Describe the bug

After upgrading our project to Quarkus 2.1.1 from 2.1.0 we noticed that our database integration tests started to fail.

Quarkus tries to start, but crashes directly with:
```
java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus
Caused by: java.lang.RuntimeException: Failed to start quarkus
Caused by: java.lang.NoClassDefFoundError: io/netty/util/concurrent/FastThreadLocal
Caused by: java.lang.ClassNotFoundException: io.netty.util.concurrent.FastThreadLocal
```

Could this be related to the work done here https://github.com/quarkusio/quarkus/pull/18925? 

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

Couldn't get a simple reproducer right now.

### Output of `uname -a` or `ver`

```
Darwin Willems-MBP.i.btp34.nl 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64
```

### Output of `java -version`

```
openjdk 11.0.11 2021-04-20 OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9) OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)
```

### GraalVM version (if different from Java)

_No response_

### Quarkus version or git rev

`2.1.1.Final`

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

```
Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d) Maven home: /Users/wjglerum/.m2/wrapper/dists/apache-maven-3.8.1-bin/2l5mhf2pq2clrde7f7qp1rdt5m/apache-maven-3.8.1 Java version: 11.0.11, vendor: AdoptOpenJDK, runtime: /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home Default locale: en_NL, platform encoding: UTF-8 OS name: "mac os x", version: "11.4", arch: "x86_64", family: "mac"
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by stuartwdouglas**
This also include some ClassLoader enhancements that allow us to exclude dependencies in unit tests, so we don't have to create a whole new module just to test this.

Fixes #19247

### CODE REVIEW

**Review by gsmet — APPROVED** [review]

File: extensions/agroal/deployment/src/test/java/io/quarkus/agroal/test/NoNettyDataSourceConfigTest.java [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+    @Inject
+    AgroalDataSource defaultDataSource;
+
+    @RegisterExtension
+    static final QuarkusUnitTest config = new QuarkusUnitTest()
+            .withConfigurationResource("base.properties")
+            //this is a bit yuck, but lots of deps used by other tests bring in Netty as transitive dependencies
+            //we need to exclude them all
+            //this removes the need to have a whole new module just for this test
+            .overrideConfigKey("quarkus.class-loading.removed-artifacts",
```
Comment (Sanne) [inline extensions/agroal/deployment/src/test/java/io/quarkus/agroal/test/NoNettyDataSourceConfigTest.java:26]: :1st_place_medal:

**Review by Sanne — APPROVED** [review]
