### ISSUE TITLE
REST Data with Panache: NoSuchMethodError for entity with a field of primitive type

### ISSUE THREAD

**Issue by olekp** [quarkusio/quarkus#30605]
### Describe the bug

When entity has a field of primitive type (even static field), listing entities via REST resource throws 'java.lang.NoSuchMethodError'. It worked in Quarkus 2.14.x

### Expected behavior

List of entities is returned via REST query

### Actual behavior

Server returns HTTP 500 due to NoSuchMethodError
```
{
  "details" : "Error id 15485abb-4251-4534-859a-6df06d254fe1-1, java.lang.NoSuchMethodError: 'javax.ws.rs.core.Response org.acme.optaplanner.rest.LessonResourceJaxRs_f8691d19a3f18a9a36549f985631a86403752779.list(java.util.List, int, int, javax.ws.rs.core.UriInfo, java.lang.String, short, java.lang.String, int, java.lang.String, java.lang.String, java.lang.Long)'",
  "stack" : "java.lang.NoSuchMethodError: 'javax.ws.rs.core.Response org.acme.optaplanner.rest.LessonResourceJaxRs_f8691d19a3f18a9a36549f985631a86403752779.list(java.util.List, int, int, javax.ws.rs.core.UriInfo, java.lang.String, short, java.lang.String, int, java.lang.String, java.lang.String, java.lang.Long)'\n\tat org.acme.optaplanner.rest.LessonResourceJaxRs_f8691d19a3f18a9a36549f985631a86403752779$quarkusrestinvoker$list_289704258f5108354a99bae0a5a9a9ea635f1ac1.invoke(Unknown Source)\n\tat org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)\n\tat io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:114)\n\tat org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)\n\tat io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)\n\tat org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)\n\tat org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)\n\tat org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)\n\tat org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)\n\tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\n\tat java.base/java.lang.Thread.run(Thread.java:833)"
}
```

### How to Reproduce?

Use https://github.com/quarkusio/quarkus-quickstarts/tree/main/optaplanner-quickstart and modify e.g **org.acme.optaplanner.domain.Lesson**:

```
@PlanningEntity
@Entity
public class Lesson {
    static final short CONST_BUG = 1; //this causes error

    @PlanningId
    @Id
    @GeneratedValue
    private Long id;

    private String subject;
    private String teacher;
    private String studentGroup;
    private int bug;    //this causes error

```

call endpoint for list of entities:
```
GET http://localhost:8080/lessons
```

### Quarkus version or git rev

2.15.3.Final

**Comment by geoand** [comment]
cc @Sgitario

**Comment by Sgitario** [comment]
This issue is caused by the changes in https://github.com/quarkusio/quarkus/pull/30554. Will fix it asap.

**Comment by Sgitario** [comment]
https://github.com/quarkusio/quarkus/pull/30626 should address this issue.
