### PR TITLE
Merge LambdaConfig with same FQN

### LINKED ISSUE #51408: Lambda extension: Failed to start quarkus because of NoSuchMethodError
### Describe the bug

We encountered a strange problem with the Lambda extension when upgrading to 3.30.2.

When starting or running the application in the tests, we get the following error:

```
        Caused by:
        java.lang.RuntimeException: Failed to start quarkus
            at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
            at io.quarkus.runtime.Application.start(Application.java:101)
            at java.base/java.lang.reflect.Method.invoke(Method.java:580)
            at io.quarkus.runner.bootstrap.StartupActionImpl.run(StartupActionImpl.java:350)
            at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:232)
            at io.quarkus.test.junit.QuarkusTestExtension.ensureStarted(QuarkusTestExtension.java:640)
            at io.quarkus.test.junit.QuarkusTestExtension.beforeAll(QuarkusTestExtension.java:685)
            ... 1 more

            Caused by:
            java.lang.NoSuchMethodError: 'java.util.Optional io.quarkus.amazon.lambda.runtime.LambdaConfig.handler()'
                at io.quarkus.amazon.lambda.runtime.AmazonLambdaRecorder.chooseHandlerClass(AmazonLambdaRecorder.java:102)
                at io.quarkus.runner.recorded.AmazonLambdaProcessor$recordHandlerClass501835388.deploy_0(Unknown Source)
                at io.quarkus.runner.recorded.AmazonLambdaProcessor$recordHandlerClass501835388.deploy(Unknown Source)
                ... 8 more
```

There are now 2 `LambdaConfig` classes in the same package `io.quarkus.amazon.lambda.runtime`.

This change comes from this [commit](https://github.com/quarkusio/quarkus/commit/b11eadc73606e5ae95db2c52957080e0c88e7706#diff-b9bdd85bf39a754f640325e3e952e8f951d8f53c903bfc19d5921992f621086d). 

I assume it's related to the problem?

### Expected behavior

Quarkus application starts and test are executed.

### Actual behavior

Quarkus application does not start.

### How to Reproduce?

A quick attempt to build a reproducer didn't work on the first try. I'll keep trying.

### Output of `uname -a` or `ver`

Darwin 24.6.0 Darwin Kernel Version 24.6.0: Mon Jul 14 11:28:30 PDT 2025; root:xnu-11417.140.69~1/RELEASE_ARM64_T6030 arm64

### Output of `java -version`

OpenJDK Runtime Environment GraalVM CE 21.0.2+13.1

### Quarkus version or git rev

3.30.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 9.2.1

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by radcortez**
- Fixes #51408

### CODE REVIEW

**Review by holly-cummins — APPROVED** [review]
Thank you!

**Comment by gsmet** [comment]
Hum. We could do that but really the problem is the split packages: we shouldn't have split packages as they are going to become a problem soon.

**Comment by radcortez** [comment]
Yes, but this is just a quick fix to be safer for backport, and we can fix the split packages in a separate PR.

Didn't we have a warning about split packages? I think we did, but when I run an example it doesn't report anything.

**Comment by gsmet** [comment]
Yeah I have seen this warning not so long ago so it's still around. Not sure why it doesn't catch this case.

**Review by geoand — APPROVED** [review]
