### ISSUE TITLE
application does not start when endpoint class in default package

### ISSUE THREAD

**Issue by vsevel** [quarkusio/quarkus#52073]
### Describe the bug

when the endpoint class is located in the default package, the application fails to start.
this is new in `3.31.0.CR1`. this is working fine in `3.30.6`

### Expected behavior

application should start. default package, while not recommended, should be supported.

### Actual behavior

it fails with:
```
17:30:09,067 ERROR [io.qua.run.Quarkus] Error running Quarkus: java.lang.ExceptionInInitializerError
        at java.base/jdk.internal.misc.Unsafe.allocateInstance(Native Method)
        at java.base/java.lang.invoke.DirectMethodHandle.allocateInstance(DirectMethodHandle.java:501)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:78)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:50)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:143)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:69)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:37)
Caused by: java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl.<clinit>(Unknown Source)
        ... 8 more
Caused by: java.lang.NoClassDefFoundError: GreetingResource_Bean
        at io.quarkus.arc.setup.Default_ComponentsProvider_addBeans0.addBeans0(Unknown Source)
        at io.quarkus.arc.setup.Default_ComponentsProvider.getComponents(Unknown Source)
        at io.quarkus.arc.impl.ArcContainerImpl.<init>(ArcContainerImpl.java:137)
        at io.quarkus.arc.Arc.initialize(Arc.java:53)
        at io.quarkus.arc.runtime.ArcRecorder.initContainer(ArcRecorder.java:53)
        at io.quarkus.runner.recorded.ArcProcessor$initializeContainer643029769.deploy_0(Unknown Source)
        at io.quarkus.runner.recorded.ArcProcessor$initializeContainer643029769.deploy(Unknown Source)
        ... 9 more
Caused by: java.lang.ClassNotFoundException: GreetingResource_Bean
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
        at io.quarkus.bootstrap.runner.RunnerClassLoader.loadClass(RunnerClassLoader.java:136)
        at io.quarkus.bootstrap.runner.RunnerClassLoader.loadClass(RunnerClassLoader.java:87)
        ... 16 more
```

### How to Reproduce?

go to https://github.com/vsevel/quarkus_reproducers/tree/quarkus_3.31.0.CR1_default_package_endpoint and follow instructions in readme.

### Quarkus version or git rev

3.31.0.CR1

**Comment by gsmet** [comment]
@mkouba @Ladicek I suspect it might be a regression caused by the new code in this area?

**Comment by mkouba** [comment]
Hm, I did try to run the reproducer in the dev mode and also run the tests but did not observe the aforementioned problem. I also tried to modify the config quickstart and everything works just fine. I'm using Temurin-25+36 (build 25+36-LTS).

@vsevel what version of Maven and Java do you use?

**Comment by vsevel** [comment]
```
vsevel@MacBook-Air-3 vsevel-quarkus_reproducers % mvn --version
Apache Maven 3.9.9 (8e8579a9e76f7d015ee5ec7bfcdc97d260186937)
Maven home: /usr/local/Cellar/maven/3.9.9/libexec
Java version: 21.0.7, vendor: Homebrew, runtime: /usr/local/Cellar/openjdk@21/21.0.7/libexec/openjdk.jdk/Contents/Home
Default locale: fr_FR, platform encoding: UTF-8
OS name: "mac os x", version: "15.7.3", arch: "x86_64", family: "mac"
vsevel@MacBook-Air-3 vsevel-quarkus_reproducers % java -jar target/quarkus-app/quarkus-run.jar                                  
vsevel@MacBook-Air-3 vsevel-quarkus_reproducers % java --version
openjdk 21.0.7 2025-04-15
OpenJDK Runtime Environment Homebrew (build 21.0.7)
OpenJDK 64-Bit Server VM Homebrew (build 21.0.7, mixed mode, sharing)
```

**Comment by vsevel** [comment]
I tested with both java 25 and 21, and I have the same error.
I created the reproducer on macos.
and we initially found it on windows.

**Comment by mkouba** [comment]
Ok, so apparently it only fails in the `prod` mode (`java -jar target/quarkus-app/quarkus-run.jar`), and not in the `dev`/`test` mode.

**Comment by geoand** [comment]
@mkouba is there anything you want to look into for this?

**Comment by mkouba** [comment]
> [@mkouba](https://github.com/mkouba) is there anything you want to look into for this?

I'm on it, thanks. I will ping you back when I find something...

**Comment by geoand** [comment]
🙏🏽

**Comment by mkouba** [comment]
And the winner is: https://github.com/quarkusio/quarkus/commit/af414686013829fdbf0e30e5c7d544281ac60fff

@gsmet Could you take a look pls?

**Comment by gsmet** [comment]
OK, luckily for us, it was just a dumb mistake I made. I will send a PR soon. Thanks @mkouba for the investigation.

**Comment by geoand** [comment]
Those damn default packages have bitten all of us many times

**Comment by gsmet** [comment]
Fix is here: https://github.com/quarkusio/quarkus/pull/52102 .
