### ISSUE TITLE
NoSuchMethodError: LambdaConfig.handler() — SmallRye ConfigMapping implementation missing handler() method in uber-jar (3.27.3.1)

### ISSUE THREAD

**Issue by sompnd** [quarkusio/quarkus#54218]
Quarkus version: 3.27.3.1 (also reproduced on 3.34.6)
Extension: quarkus-amazon-lambda-rest
Packaging: uber-jar (quarkus.package.uber-jar=true)
The LambdaConfig interface declares Optional<String> handler() ✅
The AmazonLambdaRecorder.chooseHandlerClass() calls config.handler() ✅
But the generated LambdaConfig$$CMImpl class in the uber-jar does NOT implement handler() ❌
Works fine on 3.27.0, breaks on 3.27.3.1+

This is likely related to the "legacy config classes sunsetting" work in 3.26+ that changed how @ConfigRoot + @ConfigMapping interfaces are processed. The handler() property is being dropped during the config mapping implementation generation.

**Comment by geoand** [comment]
Thanks for reporting.

Can you please update the description to **not** use bullet points as they make it very hard to get any details out of it.

Also, if you could format the code parts, it would be help.

**Comment by radcortez** [comment]
Also, any chance to provide us with a reproducer? Thank you!

**Comment by gsmet** [comment]
I don't have a reproducer so hard to check but I can see why you would encounter this in 3.27, https://github.com/quarkusio/quarkus/pull/51410 fixed the issue but was never backported.

The issue was introduced by https://github.com/quarkusio/quarkus/pull/51734 that was included in 3.27.2.

I fail to see how you could reproduce it with 3.34.6 though as the fix has been merged for quite a while.

I will mark the fix as a candidate for backport to 3.27 (we need to be more careful about this!). We will include it in the next 3.27.x.

I will close this but if you can effectively reproduce it with 3.34.6, please reopen with a reproducer.
