### ISSUE TITLE
Lombok not working on 2.3.0.Final

### ISSUE THREAD

**Issue by ducmami** [quarkusio/quarkus#20811]
### Describe the bug

When i upgrade Quarkus from 2.2.3.Final to 2.3.0.Final
Lombok seemly not working

`error: cannot find symbol
        log.info("demo that log");
        ^
  symbol:   variable log`

**Comment by ducmami** [comment]
Thank you so much.
