### PR TITLE
Use custom ClassLoader with visible defineClass when generating proxies

### LINKED ISSUE #1534: Java 12 build fails: Could not initialize class org.jboss.classfilewriter.DefaultClassFactory
This issue looks very similar to #819, but it is a different class (from probably the same library):

Running our build with Quarkus 0.11.0 on JDK 12 fails:

_Could not initialize class org.jboss.classfilewriter.DefaultClassFactory_

```
java.lang.RuntimeException: 
org.jboss.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.deployment.logging.LoggingResourceProcessor#setupLoggingRuntimeInit threw an exception: java.lang.Error: java.lang.NoSuchFieldException: override
	[error]: Build step io.quarkus.deployment.logging.LoggingResourceProcessor#setupLoggingStaticInit threw an exception: java.lang.NoClassDefFoundError: Could not initialize class org.jboss.classfilewriter.DefaultClassFactory
Caused by: org.jboss.builder.BuildException: 
Build failure: Build failed due to errors
	[error]: Build step io.quarkus.deployment.logging.LoggingResourceProcessor#setupLoggingRuntimeInit threw an exception: java.lang.Error: java.lang.NoSuchFieldException: override
	[error]: Build step io.quarkus.deployment.logging.LoggingResourceProcessor#setupLoggingStaticInit threw an exception: java.lang.NoClassDefFoundError: Could not initialize class org.jboss.classfilewriter.DefaultClassFactory
Caused by: java.lang.Error: java.lang.NoSuchFieldException: override
Caused by: java.lang.NoSuchFieldException: override
```

You will find the full build-output here: https://travis-ci.org/mapstruct/mapstruct-examples/jobs/506375906 (I am not sure if these logs will be discarded after time).

Java version details:

> openjdk version "12" 2019-03-19
> OpenJDK Runtime Environment (build 12+33)
> OpenJDK 64-Bit Server VM (build 12+33, mixed mode, sharing)

In case you need more information please let me know.

_(nevertheless, thank you very much for Quarkus - just did a few tests with the library and it looks gorgeous!)_

### PR DESCRIPTION
**Pull request by geoand**
This makes sense for Quarkus where the ClassLoader is under our control.
The benefit is that proxy classes can be generated no matter what JDK
version is being used (so now proxies can be generated even in JDK 12+)

Fixes: #1534

### CODE REVIEW

**Comment by maxandersen** [comment]
here is my +1 to confirm that with this PR I can run the getting-started quickstart on java 12 and 13 !

**Review by dmlloyd — APPROVED** [review]
Looks good!

**Comment by maxandersen** [comment]
just to pile on, also verified it works on java 11 and java 14. yay.

**Comment by geoand** [comment]
Thanks!
