### ISSUE TITLE
Quarkus 1.7.x: Gradle Kotlin project compilation error

### ISSUE THREAD

**Issue by andreas-eberle** [quarkusio/quarkus#11641]
**Describe the bug**
After upgrading my Quarkus (gradle, Kotlin) project from 1.6.1.Final to 1.7.0.Final, I get a compilation error 

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':common:quarkusPrepareTests'.
> Cannot change dependencies of dependency configuration ':common:kotlinCompilerPluginClasspath' after it has been resolved.

```

**To Reproduce**
1. Download reproducer project and unzip it [2020-08-25_kotlin-compiling-issues.zip](https://github.com/quarkusio/quarkus/files/5129529/2020-08-25_kotlin-compiling-issues.zip)
2. Run `./gradlew check` in the project directory
3. The build fails with the error shown above
4. Change the Quarkus version in gradle.properties to 1.6.1.Final and it works

**Environment (please complete the following information):**
 - Quarkus 1.7.0
- Windows 10
- JDK 11

**Comment by andreas-eberle** [comment]
@glefloch

**Comment by andreas-eberle** [comment]
This error still exists in Quarkus 1.7.1.

**Comment by glefloch** [comment]
Yes, just found a fix, the `quarkusPrepare` tasks need to be run before any kotlin compilation. 
I need to create an integration test and I will open a pull request. 
If you don't have grpc code generation, you can just skip `quarkusPrepare` and `quarkusPrepareTest` tasks as a workaround.

**Comment by gsmet** [comment]
@glefloch just to make you aware of: https://github.com/quarkusio/quarkus/pull/11624

**Comment by glefloch** [comment]
Thanks @gsmet I will rebase my branch.

**Comment by andreas-eberle** [comment]
@glefloch: Thanks! Sounds great. Looking forward to the fix :)

**Comment by yuce** [comment]
I've encountered this problem on Kotlin 1.3.72 + Quarkus 1.7.1 when using `./gradlew build -Dquarkus.package.type=native`. Using `./gradlew buildNative` works fine.
`

**Comment by MartinX3** [comment]
Oh I assume we won't get a Quarkus 1.7.2 hotfix release?
We are not able to run JUnit tests anymore.
